<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$entries = [
			[
				'code'               => 'AED',
				'name'               => 'United Arab Emirates Dirham',
				'html_entity'        => '&#1583;.&#1573;',
				'font_arial'         => 'د.إ',
				'font_code2000'      => 'د.إ',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'AFN',
				'name'               => 'Afghanistan Afghani',
				'html_entity'        => '&#65;&#102;',
				'font_arial'         => '؋',
				'font_code2000'      => '؋',
				'unicode_decimal'    => '1547',
				'unicode_hex'        => '60b',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'ALL',
				'name'               => 'Albania Lek',
				'html_entity'        => '&#76;&#101;&#107;',
				'font_arial'         => 'Lek',
				'font_code2000'      => 'Lek',
				'unicode_decimal'    => '76, 1',
				'unicode_hex'        => '4c, 6',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'AMD',
				'name'               => 'Armenia Dram',
				'html_entity'        => '',
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'ANG',
				'name'               => 'Netherlands Antilles Guilder',
				'html_entity'        => '&#402;',
				'font_arial'         => 'ƒ',
				'font_code2000'      => 'ƒ',
				'unicode_decimal'    => '402',
				'unicode_hex'        => '192',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'AOA',
				'name'               => 'Angola Kwanza',
				'html_entity'        => '&#75;&#122;',
				'font_arial'         => 'Kz',
				'font_code2000'      => 'Kz',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'ARS',
				'name'               => 'Argentina Peso',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'AUD',
				'name'               => 'Australia Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'AWG',
				'name'               => 'Aruba Guilder',
				'html_entity'        => '&#402;',
				'font_arial'         => 'ƒ',
				'font_code2000'      => 'ƒ',
				'unicode_decimal'    => '402',
				'unicode_hex'        => '192',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'AZN',
				'name'               => 'Azerbaijan New Manat',
				'html_entity'        => '&#1084;&#1072;&#1085;',
				'font_arial'         => 'ман',
				'font_code2000'      => 'ман',
				'unicode_decimal'    => '1084,',
				'unicode_hex'        => '43c, ',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'BAM',
				'name'               => 'Bosnia and Herzegovina Convertible Marka',
				'html_entity'        => '&#75;&#77;',
				'font_arial'         => 'KM',
				'font_code2000'      => 'KM',
				'unicode_decimal'    => '75, 7',
				'unicode_hex'        => '4b, 4',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'BBD',
				'name'               => 'Barbados Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'BDT',
				'name'               => 'Bangladesh Taka',
				'html_entity'        => '&#2547;',
				'font_arial'         => '৳',
				'font_code2000'      => '৳',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'BGN',
				'name'               => 'Bulgaria Lev',
				'html_entity'        => '&#1083;&#1074;',
				'font_arial'         => 'лв',
				'font_code2000'      => 'лв',
				'unicode_decimal'    => '1083,',
				'unicode_hex'        => '43b, ',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'BHD',
				'name'               => 'Bahrain Dinar',
				'html_entity'        => '.&#1583;.&#1576;',
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '3',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'BIF',
				'name'               => 'Burundi Franc',
				'html_entity'        => '&#70;&#66;&#117;',
				'font_arial'         => 'FBu',
				'font_code2000'      => 'FBu',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'BMD',
				'name'               => 'Bermuda Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'BND',
				'name'               => 'Brunei Darussalam Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'BOB',
				'name'               => 'Bolivia Boliviano',
				'html_entity'        => '&#36;&#98;',
				'font_arial'         => '$b',
				'font_code2000'      => '$b',
				'unicode_decimal'    => '36, 9',
				'unicode_hex'        => '24, 6',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'BRL',
				'name'               => 'Brazil Real',
				'html_entity'        => '&#82;&#36;',
				'font_arial'         => 'R$',
				'font_code2000'      => 'R$',
				'unicode_decimal'    => '82, 3',
				'unicode_hex'        => '52, 2',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'BSD',
				'name'               => 'Bahamas Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'BTN',
				'name'               => 'Bhutan Ngultrum',
				'html_entity'        => '&#78;&#117;&#46;',
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'BWP',
				'name'               => 'Botswana Pula',
				'html_entity'        => '&#80;',
				'font_arial'         => 'P',
				'font_code2000'      => 'P',
				'unicode_decimal'    => '80',
				'unicode_hex'        => '50',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'BYR',
				'name'               => 'Belarus Ruble',
				'html_entity'        => '&#112;&#46;',
				'font_arial'         => 'p.',
				'font_code2000'      => 'p.',
				'unicode_decimal'    => '112, ',
				'unicode_hex'        => '70, 2',
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'BZD',
				'name'               => 'Belize Dollar',
				'html_entity'        => '&#66;&#90;&#36;',
				'font_arial'         => 'BZ$',
				'font_code2000'      => 'BZ$',
				'unicode_decimal'    => '66, 9',
				'unicode_hex'        => '42, 5',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'CAD',
				'name'               => 'Canada Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'CDF',
				'name'               => 'Congo/Kinshasa Franc',
				'html_entity'        => '&#70;&#67;',
				'font_arial'         => 'Fr',
				'font_code2000'      => 'Fr',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'CHF',
				'name'               => 'Switzerland Franc',
				'html_entity'        => '&#67;&#72;&#70;',
				'font_arial'         => 'Fr',
				'font_code2000'      => 'Fr',
				'unicode_decimal'    => '67, 7',
				'unicode_hex'        => '43, 4',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'CLP',
				'name'               => 'Chile Peso',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'CNY',
				'name'               => 'China Yuan Renminbi',
				'html_entity'        => '&#165;',
				'font_arial'         => '¥',
				'font_code2000'      => '¥',
				'unicode_decimal'    => '165',
				'unicode_hex'        => 'a5',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'COP',
				'name'               => 'Colombia Peso',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'CRC',
				'name'               => 'Costa Rica Colon',
				'html_entity'        => '&#8353;',
				'font_arial'         => '₡',
				'font_code2000'      => '₡',
				'unicode_decimal'    => '8353',
				'unicode_hex'        => '20a1',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'CUC',
				'name'               => 'Cuba Convertible Peso',
				'html_entity'        => null,
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'CUP',
				'name'               => 'Cuba Peso',
				'html_entity'        => '&#8396;',
				'font_arial'         => '₱',
				'font_code2000'      => '₱',
				'unicode_decimal'    => '8369',
				'unicode_hex'        => '20b1',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'CVE',
				'name'               => 'Cape Verde Escudo',
				'html_entity'        => '&#x24;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '1',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'CZK',
				'name'               => 'Czech Republic Koruna',
				'html_entity'        => '&#75;&#269;',
				'font_arial'         => 'Kč',
				'font_code2000'      => 'Kč',
				'unicode_decimal'    => '75, 2',
				'unicode_hex'        => '4b, 1',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'DJF',
				'name'               => 'Djibouti Franc',
				'html_entity'        => '&#70;&#100;&#106;',
				'font_arial'         => 'Fr',
				'font_code2000'      => 'Fr',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'DKK',
				'name'               => 'Denmark Krone',
				'html_entity'        => '&#107;&#114;',
				'font_arial'         => 'kr',
				'font_code2000'      => 'kr',
				'unicode_decimal'    => '107, ',
				'unicode_hex'        => '6b, 7',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'DOP',
				'name'               => 'Dominican Republic Peso',
				'html_entity'        => '&#82;&#68;&#36;',
				'font_arial'         => 'RD$',
				'font_code2000'      => 'RD$',
				'unicode_decimal'    => '82, 6',
				'unicode_hex'        => '52, 4',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'DZD',
				'name'               => 'Algeria Dinar',
				'html_entity'        => '&#1583;&#1580;',
				'font_arial'         => 'DA',
				'font_code2000'      => 'DA',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'EEK',
				'name'               => 'Estonia Kroon',
				'html_entity'        => null,
				'font_arial'         => 'kr',
				'font_code2000'      => 'kr',
				'unicode_decimal'    => '107, ',
				'unicode_hex'        => '6b, 7',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'EGP',
				'name'               => 'Egypt Pound',
				'html_entity'        => '&#163;',
				'font_arial'         => '£',
				'font_code2000'      => '£',
				'unicode_decimal'    => '163',
				'unicode_hex'        => 'a3',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'ERN',
				'name'               => 'Eritrea Nakfa',
				'html_entity'        => '&#x4E;&#x66;&#x6B;',
				'font_arial'         => 'Nfk',
				'font_code2000'      => 'Nfk',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'ETB',
				'name'               => 'Ethiopia Birr',
				'html_entity'        => '&#66;&#114;',
				'font_arial'         => 'Br',
				'font_code2000'      => 'Br',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'EUR',
				'name'               => 'Euro Member Countries',
				'html_entity'        => '€',
				'font_arial'         => '€',
				'font_code2000'      => '€',
				'unicode_decimal'    => '8364',
				'unicode_hex'        => '20ac',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => ',',
				'thousand_separator' => ' ',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'FJD',
				'name'               => 'Fiji Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'FKP',
				'name'               => 'Falkland Islands (Malvinas) Pound',
				'html_entity'        => '&#163;',
				'font_arial'         => '£',
				'font_code2000'      => '£',
				'unicode_decimal'    => '163',
				'unicode_hex'        => 'a3',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'GBP',
				'name'               => 'United Kingdom Pound',
				'html_entity'        => '&#163;',
				'font_arial'         => '£',
				'font_code2000'      => '£',
				'unicode_decimal'    => '163',
				'unicode_hex'        => 'a3',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'GEL',
				'name'               => 'Georgia Lari',
				'html_entity'        => '&#4314;',
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'GGP',
				'name'               => 'Guernsey Pound',
				'html_entity'        => null,
				'font_arial'         => '£',
				'font_code2000'      => '£',
				'unicode_decimal'    => '163',
				'unicode_hex'        => 'a3',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'GHC',
				'name'               => 'Ghana Cedi',
				'html_entity'        => '&#x47;&#x48;&#xA2;',
				'font_arial'         => 'GH¢',
				'font_code2000'      => 'GH¢',
				'unicode_decimal'    => '162',
				'unicode_hex'        => 'a2',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'GHS',
				'name'               => 'Ghana Cedi',
				'html_entity'        => '&#x47;&#x48;&#xA2;',
				'font_arial'         => 'GH¢',
				'font_code2000'      => 'GH¢',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'GIP',
				'name'               => 'Gibraltar Pound',
				'html_entity'        => '&#163;',
				'font_arial'         => '£',
				'font_code2000'      => '£',
				'unicode_decimal'    => '163',
				'unicode_hex'        => 'a3',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'GMD',
				'name'               => 'Gambia Dalasi',
				'html_entity'        => '&#68;',
				'font_arial'         => 'D',
				'font_code2000'      => 'D',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'GNF',
				'name'               => 'Guinea Franc',
				'html_entity'        => '&#70;&#71;',
				'font_arial'         => 'Fr',
				'font_code2000'      => 'Fr',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'GTQ',
				'name'               => 'Guatemala Quetzal',
				'html_entity'        => '&#81;',
				'font_arial'         => 'Q',
				'font_code2000'      => 'Q',
				'unicode_decimal'    => '81',
				'unicode_hex'        => '51',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'GYD',
				'name'               => 'Guyana Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'HKD',
				'name'               => 'Hong Kong Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'HNL',
				'name'               => 'Honduras Lempira',
				'html_entity'        => '&#76;',
				'font_arial'         => 'L',
				'font_code2000'      => 'L',
				'unicode_decimal'    => '76',
				'unicode_hex'        => '4c',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'HRK',
				'name'               => 'Croatia Kuna',
				'html_entity'        => '&#107;&#110;',
				'font_arial'         => 'kn',
				'font_code2000'      => 'kn',
				'unicode_decimal'    => '107, ',
				'unicode_hex'        => '6b, 6',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'HTG',
				'name'               => 'Haiti Gourde',
				'html_entity'        => '&#71;',
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'HUF',
				'name'               => 'Hungary Forint',
				'html_entity'        => '&#70;&#116;',
				'font_arial'         => 'Ft',
				'font_code2000'      => 'Ft',
				'unicode_decimal'    => '70, 1',
				'unicode_hex'        => '46, 7',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'IDR',
				'name'               => 'Indonesia Rupiah',
				'html_entity'        => '&#82;&#112;',
				'font_arial'         => 'Rp',
				'font_code2000'      => 'Rp',
				'unicode_decimal'    => '82, 1',
				'unicode_hex'        => '52, 7',
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'ILS',
				'name'               => 'Israel Shekel',
				'html_entity'        => '&#8362;',
				'font_arial'         => '₪',
				'font_code2000'      => '₪',
				'unicode_decimal'    => '8362',
				'unicode_hex'        => '20aa',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'IMP',
				'name'               => 'Isle of Man Pound',
				'html_entity'        => null,
				'font_arial'         => '£',
				'font_code2000'      => '£',
				'unicode_decimal'    => '163',
				'unicode_hex'        => 'a3',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'INR',
				'name'               => 'India Rupee',
				'html_entity'        => '&#8377;',
				'font_arial'         => '₨',
				'font_code2000'      => '₨',
				'unicode_decimal'    => '',
				'unicode_hex'        => '',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'IQD',
				'name'               => 'Iraq Dinar',
				'html_entity'        => '&#1593;.&#1583;',
				'font_arial'         => 'د.ع;',
				'font_code2000'      => 'د.ع;',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'IRR',
				'name'               => 'Iran Rial',
				'html_entity'        => '&#65020;',
				'font_arial'         => '﷼',
				'font_code2000'      => '﷼',
				'unicode_decimal'    => '65020',
				'unicode_hex'        => 'fdfc',
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'ISK',
				'name'               => 'Iceland Krona',
				'html_entity'        => '&#107;&#114;',
				'font_arial'         => 'kr',
				'font_code2000'      => 'kr',
				'unicode_decimal'    => '107, ',
				'unicode_hex'        => '6b, 7',
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'JEP',
				'name'               => 'Jersey Pound',
				'html_entity'        => '&#163;',
				'font_arial'         => '£',
				'font_code2000'      => '£',
				'unicode_decimal'    => '163',
				'unicode_hex'        => 'a3',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'JMD',
				'name'               => 'Jamaica Dollar',
				'html_entity'        => '&#74;&#36;',
				'font_arial'         => 'J$',
				'font_code2000'      => 'J$',
				'unicode_decimal'    => '74, 3',
				'unicode_hex'        => '4a, 2',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'JOD',
				'name'               => 'Jordan Dinar',
				'html_entity'        => '&#74;&#68;',
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '3',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'JPY',
				'name'               => 'Japan Yen',
				'html_entity'        => '&#165;',
				'font_arial'         => '¥',
				'font_code2000'      => '¥',
				'unicode_decimal'    => '165',
				'unicode_hex'        => 'a5',
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'KES',
				'name'               => 'Kenya Shilling',
				'html_entity'        => '&#x4B;&#x53;&#x68;',
				'font_arial'         => 'KSh',
				'font_code2000'      => 'KSh',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'KGS',
				'name'               => 'Kyrgyzstan Som',
				'html_entity'        => '&#1083;&#1074;',
				'font_arial'         => 'лв',
				'font_code2000'      => 'лв',
				'unicode_decimal'    => '1083,',
				'unicode_hex'        => '43b, ',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'KHR',
				'name'               => 'Cambodia Riel',
				'html_entity'        => '&#6107;',
				'font_arial'         => '៛',
				'font_code2000'      => '៛',
				'unicode_decimal'    => '6107',
				'unicode_hex'        => '17db',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'KMF',
				'name'               => 'Comoros Franc',
				'html_entity'        => '&#67;&#70;',
				'font_arial'         => 'Fr',
				'font_code2000'      => 'Fr',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'KPW',
				'name'               => 'Korea (North) Won',
				'html_entity'        => '&#8361;',
				'font_arial'         => '₩',
				'font_code2000'      => '₩',
				'unicode_decimal'    => '8361',
				'unicode_hex'        => '20a9',
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'KRW',
				'name'               => 'Korea (South) Won',
				'html_entity'        => '&#8361;',
				'font_arial'         => '₩',
				'font_code2000'      => '₩',
				'unicode_decimal'    => '8361',
				'unicode_hex'        => '20a9',
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'KWD',
				'name'               => 'Kuwait Dinar',
				'html_entity'        => '&#1583;.&#1603;',
				'font_arial'         => 'د.ك',
				'font_code2000'      => 'د.ك',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'KYD',
				'name'               => 'Cayman Islands Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'KZT',
				'name'               => 'Kazakhstan Tenge',
				'html_entity'        => '&#1083;&#1074;',
				'font_arial'         => 'лв',
				'font_code2000'      => 'лв',
				'unicode_decimal'    => '1083,',
				'unicode_hex'        => '43b, ',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'LAK',
				'name'               => 'Laos Kip',
				'html_entity'        => '&#8365;',
				'font_arial'         => '₭',
				'font_code2000'      => '₭',
				'unicode_decimal'    => '8365',
				'unicode_hex'        => '20ad',
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'LBP',
				'name'               => 'Lebanon Pound',
				'html_entity'        => '&#163;',
				'font_arial'         => '£',
				'font_code2000'      => '£',
				'unicode_decimal'    => '163',
				'unicode_hex'        => 'a3',
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'LKR',
				'name'               => 'Sri Lanka Rupee',
				'html_entity'        => '&#8360;',
				'font_arial'         => '₨',
				'font_code2000'      => '₨',
				'unicode_decimal'    => '8360',
				'unicode_hex'        => '20a8',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'LRD',
				'name'               => 'Liberia Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'LSL',
				'name'               => 'Lesotho Loti',
				'html_entity'        => '&#76;',
				'font_arial'         => 'M',
				'font_code2000'      => 'M',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'LTL',
				'name'               => 'Lithuania Litas',
				'html_entity'        => '&#76;&#116;',
				'font_arial'         => 'Lt',
				'font_code2000'      => 'Lt',
				'unicode_decimal'    => '76, 1',
				'unicode_hex'        => '4c, 7',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'LVL',
				'name'               => 'Latvia Lat',
				'html_entity'        => '&#76;&#115;',
				'font_arial'         => 'Ls',
				'font_code2000'      => 'Ls',
				'unicode_decimal'    => '76, 1',
				'unicode_hex'        => '4c, 7',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'LYD',
				'name'               => 'Libya Dinar',
				'html_entity'        => '&#1604;.&#1583;',
				'font_arial'         => 'DL',
				'font_code2000'      => 'DL',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '3',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'MAD',
				'name'               => 'Morocco Dirham',
				'html_entity'        => '&#1583;.&#1605;.',
				'font_arial'         => 'Dhs',
				'font_code2000'      => 'Dhs',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'MDL',
				'name'               => 'Moldova Leu',
				'html_entity'        => '&#76;',
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'MGA',
				'name'               => 'Madagascar Ariary',
				'html_entity'        => '&#65;&#114;',
				'font_arial'         => 'Ar',
				'font_code2000'      => 'Ar',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '5',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'MKD',
				'name'               => 'Macedonia Denar',
				'html_entity'        => '&#1076;&#1077;&#1085;',
				'font_arial'         => 'ден',
				'font_code2000'      => 'ден',
				'unicode_decimal'    => '1076,',
				'unicode_hex'        => '434, ',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'MMK',
				'name'               => 'Myanmar (Burma) Kyat',
				'html_entity'        => '&#75;',
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'MNT',
				'name'               => 'Mongolia Tughrik',
				'html_entity'        => '&#8366;',
				'font_arial'         => '₮',
				'font_code2000'      => '₮',
				'unicode_decimal'    => '8366',
				'unicode_hex'        => '20ae',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'MOP',
				'name'               => 'Macau Pataca',
				'html_entity'        => '&#77;&#79;&#80;&#36;',
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '1',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'MRO',
				'name'               => 'Mauritania Ouguiya',
				'html_entity'        => '&#85;&#77;',
				'font_arial'         => 'UM',
				'font_code2000'      => 'UM',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '5',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'MUR',
				'name'               => 'Mauritius Rupee',
				'html_entity'        => '&#8360;',
				'font_arial'         => '₨',
				'font_code2000'      => '₨',
				'unicode_decimal'    => '8360',
				'unicode_hex'        => '20a8',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'MVR',
				'name'               => 'Maldives (Maldive Islands) Rufiyaa',
				'html_entity'        => '.&#1923;',
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'MWK',
				'name'               => 'Malawi Kwacha',
				'html_entity'        => '&#77;&#75;',
				'font_arial'         => 'MK',
				'font_code2000'      => 'MK',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'MXN',
				'name'               => 'Mexico Peso',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'MYR',
				'name'               => 'Malaysia Ringgit',
				'html_entity'        => '&#82;&#77;',
				'font_arial'         => 'RM',
				'font_code2000'      => 'RM',
				'unicode_decimal'    => '82, 7',
				'unicode_hex'        => '52, 4',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'MZN',
				'name'               => 'Mozambique Metical',
				'html_entity'        => '&#77;&#84;',
				'font_arial'         => 'MT',
				'font_code2000'      => 'MT',
				'unicode_decimal'    => '77, 8',
				'unicode_hex'        => '4d, 5',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'NAD',
				'name'               => 'Namibia Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'NGN',
				'name'               => 'Nigeria Naira',
				'html_entity'        => '&#8358;',
				'font_arial'         => '₦',
				'font_code2000'      => '₦',
				'unicode_decimal'    => '8358',
				'unicode_hex'        => '20a6',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'NIO',
				'name'               => 'Nicaragua Cordoba',
				'html_entity'        => '&#67;&#36;',
				'font_arial'         => 'C$',
				'font_code2000'      => 'C$',
				'unicode_decimal'    => '67, 3',
				'unicode_hex'        => '43, 2',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'NOK',
				'name'               => 'Norway Krone',
				'html_entity'        => '&#107;&#114;',
				'font_arial'         => 'kr',
				'font_code2000'      => 'kr',
				'unicode_decimal'    => '107, ',
				'unicode_hex'        => '6b, 7',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'NPR',
				'name'               => 'Nepal Rupee',
				'html_entity'        => '&#8360;',
				'font_arial'         => '₨',
				'font_code2000'      => '₨',
				'unicode_decimal'    => '8360',
				'unicode_hex'        => '20a8',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'NZD',
				'name'               => 'New Zealand Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'OMR',
				'name'               => 'Oman Rial',
				'html_entity'        => '&#65020;',
				'font_arial'         => '﷼',
				'font_code2000'      => '﷼',
				'unicode_decimal'    => '65020',
				'unicode_hex'        => 'fdfc',
				'in_left'            => '0',
				'decimal_places'     => '3',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'PAB',
				'name'               => 'Panama Balboa',
				'html_entity'        => '&#66;&#47;&#46;',
				'font_arial'         => 'B/.',
				'font_code2000'      => 'B/.',
				'unicode_decimal'    => '66, 4',
				'unicode_hex'        => '42, 2',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'PEN',
				'name'               => 'Peru Nuevo Sol',
				'html_entity'        => '&#83;&#47;&#46;',
				'font_arial'         => 'S/.',
				'font_code2000'      => 'S/.',
				'unicode_decimal'    => '83, 4',
				'unicode_hex'        => '53, 2',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'PGK',
				'name'               => 'Papua New Guinea Kina',
				'html_entity'        => '&#75;',
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'PHP',
				'name'               => 'Philippines Peso',
				'html_entity'        => '&#8369;',
				'font_arial'         => '₱',
				'font_code2000'      => '₱',
				'unicode_decimal'    => '8369',
				'unicode_hex'        => '20b1',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'PKR',
				'name'               => 'Pakistan Rupee',
				'html_entity'        => '&#8360;',
				'font_arial'         => '₨',
				'font_code2000'      => '₨',
				'unicode_decimal'    => '8360',
				'unicode_hex'        => '20a8',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'PLN',
				'name'               => 'Poland Zloty',
				'html_entity'        => '&#122;&#322;',
				'font_arial'         => 'zł',
				'font_code2000'      => 'zł',
				'unicode_decimal'    => '122, ',
				'unicode_hex'        => '7a, 1',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'PYG',
				'name'               => 'Paraguay Guarani',
				'html_entity'        => '&#71;&#115;',
				'font_arial'         => 'Gs',
				'font_code2000'      => 'Gs',
				'unicode_decimal'    => '71, 1',
				'unicode_hex'        => '47, 7',
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'QAR',
				'name'               => 'Qatar Riyal',
				'html_entity'        => '&#65020;',
				'font_arial'         => '﷼',
				'font_code2000'      => '﷼',
				'unicode_decimal'    => '65020',
				'unicode_hex'        => 'fdfc',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'RON',
				'name'               => 'Romania New Leu',
				'html_entity'        => '&#108;&#101;&#105;',
				'font_arial'         => 'lei',
				'font_code2000'      => 'lei',
				'unicode_decimal'    => '108, ',
				'unicode_hex'        => '6c, 6',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'RSD',
				'name'               => 'Serbia Dinar',
				'html_entity'        => '&#1044;&#1080;&#1085;&#46;',
				'font_arial'         => 'Дин.',
				'font_code2000'      => 'Дин.',
				'unicode_decimal'    => '1044,',
				'unicode_hex'        => '414, ',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'RUB',
				'name'               => 'Russia Ruble',
				'html_entity'        => '&#8381;',
				'font_arial'         => '₽',
				'font_code2000'      => '₽',
				'unicode_decimal'    => '8381,',
				'unicode_hex'        => '20BD',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'RWF',
				'name'               => 'Rwanda Franc',
				'html_entity'        => '&#1585;.&#1587;',
				'font_arial'         => 'FRw',
				'font_code2000'      => 'FRw',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'SAR',
				'name'               => 'Saudi Arabia Riyal',
				'html_entity'        => '&#65020;',
				'font_arial'         => '﷼',
				'font_code2000'      => '﷼',
				'unicode_decimal'    => '65020',
				'unicode_hex'        => 'fdfc',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'SBD',
				'name'               => 'Solomon Islands Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'SCR',
				'name'               => 'Seychelles Rupee',
				'html_entity'        => '&#8360;',
				'font_arial'         => '₨',
				'font_code2000'      => '₨',
				'unicode_decimal'    => '8360',
				'unicode_hex'        => '20a8',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'SDG',
				'name'               => 'Sudan Pound',
				'html_entity'        => '&#163;',
				'font_arial'         => 'DS',
				'font_code2000'      => 'DS',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'SEK',
				'name'               => 'Sweden Krona',
				'html_entity'        => '&#107;&#114;',
				'font_arial'         => 'kr',
				'font_code2000'      => 'kr',
				'unicode_decimal'    => '107, ',
				'unicode_hex'        => '6b, 7',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'SGD',
				'name'               => 'Singapore Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'SHP',
				'name'               => 'Saint Helena Pound',
				'html_entity'        => '&#163;',
				'font_arial'         => '£',
				'font_code2000'      => '£',
				'unicode_decimal'    => '163',
				'unicode_hex'        => 'a3',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'SLL',
				'name'               => 'Sierra Leone Leone',
				'html_entity'        => '&#76;&#101;',
				'font_arial'         => 'Le',
				'font_code2000'      => 'Le',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '1',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'SOS',
				'name'               => 'Somalia Shilling',
				'html_entity'        => '&#83;',
				'font_arial'         => 'S',
				'font_code2000'      => 'S',
				'unicode_decimal'    => '83',
				'unicode_hex'        => '53',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'SPL',
				'name'               => 'Seborga Luigino',
				'html_entity'        => null,
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'SRD',
				'name'               => 'Suriname Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'SSP',
				'name'               => 'South Sudanese Pound',
				'html_entity'        => '&#xA3;',
				'font_arial'         => '£',
				'font_code2000'      => '£',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'STD',
				'name'               => 'São Tomé and Príncipe Dobra',
				'html_entity'        => '&#68;&#98;',
				'font_arial'         => 'Db',
				'font_code2000'      => 'Db',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'SVC',
				'name'               => 'El Salvador Colon',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'SYP',
				'name'               => 'Syria Pound',
				'html_entity'        => '&#163;',
				'font_arial'         => '£',
				'font_code2000'      => '£',
				'unicode_decimal'    => '163',
				'unicode_hex'        => 'a3',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'SZL',
				'name'               => 'Swaziland Lilangeni',
				'html_entity'        => '&#76;',
				'font_arial'         => 'E',
				'font_code2000'      => 'E',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'THB',
				'name'               => 'Thailand Baht',
				'html_entity'        => '&#3647;',
				'font_arial'         => '฿',
				'font_code2000'      => '฿',
				'unicode_decimal'    => '3647',
				'unicode_hex'        => 'e3f',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'TJS',
				'name'               => 'Tajikistan Somoni',
				'html_entity'        => '&#84;&#74;&#83;',
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'TMT',
				'name'               => 'Turkmenistan Manat',
				'html_entity'        => '&#109;',
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'TND',
				'name'               => 'Tunisia Dinar',
				'html_entity'        => '&#1583;.&#1578;',
				'font_arial'         => 'DT',
				'font_code2000'      => 'DT',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '1',
				'decimal_places'     => '3',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'TOP',
				'name'               => 'Tonga Pa\'anga',
				'html_entity'        => '&#84;&#36;',
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'TRL',
				'name'               => 'Turkey Lira',
				'html_entity'        => null,
				'font_arial'         => '₤',
				'font_code2000'      => '₤',
				'unicode_decimal'    => '8356',
				'unicode_hex'        => '20a4',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'TRY',
				'name'               => 'Turkey Lira',
				'html_entity'        => '&#x20BA;',
				'font_arial'         => '₺',
				'font_code2000'      => '₺',
				'unicode_decimal'    => '',
				'unicode_hex'        => '',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'TTD',
				'name'               => 'Trinidad and Tobago Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => 'TT$',
				'font_code2000'      => 'TT$',
				'unicode_decimal'    => '84, 8',
				'unicode_hex'        => '54, 5',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'TVD',
				'name'               => 'Tuvalu Dollar',
				'html_entity'        => null,
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'TWD',
				'name'               => 'Taiwan New Dollar',
				'html_entity'        => '&#78;&#84;&#36;',
				'font_arial'         => 'NT$',
				'font_code2000'      => 'NT$',
				'unicode_decimal'    => '78, 8',
				'unicode_hex'        => '4e, 5',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'TZS',
				'name'               => 'Tanzania Shilling',
				'html_entity'        => '&#x54;&#x53;&#x68;',
				'font_arial'         => 'TSh',
				'font_code2000'      => 'TSh',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'UAH',
				'name'               => 'Ukraine Hryvnia',
				'html_entity'        => '&#8372;',
				'font_arial'         => '₴',
				'font_code2000'      => '₴',
				'unicode_decimal'    => '8372',
				'unicode_hex'        => '20b4',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'UGX',
				'name'               => 'Uganda Shilling',
				'html_entity'        => '&#85;&#83;&#104;',
				'font_arial'         => 'USh',
				'font_code2000'      => 'USh',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'USD',
				'name'               => 'United States Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'UYU',
				'name'               => 'Uruguay Peso',
				'html_entity'        => '&#36;&#85;',
				'font_arial'         => '$U',
				'font_code2000'      => '$U',
				'unicode_decimal'    => '36, 8',
				'unicode_hex'        => '24, 5',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'UZS',
				'name'               => 'Uzbekistan Som',
				'html_entity'        => '&#1083;&#1074;',
				'font_arial'         => 'лв',
				'font_code2000'      => 'лв',
				'unicode_decimal'    => '1083,',
				'unicode_hex'        => '43b, ',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'VEF',
				'name'               => 'Venezuela Bolivar',
				'html_entity'        => '&#66;&#115;',
				'font_arial'         => 'Bs',
				'font_code2000'      => 'Bs',
				'unicode_decimal'    => '66, 1',
				'unicode_hex'        => '42, 7',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'VND',
				'name'               => 'Viet Nam Dong',
				'html_entity'        => '&#8363;',
				'font_arial'         => '₫',
				'font_code2000'      => '₫',
				'unicode_decimal'    => '8363',
				'unicode_hex'        => '20ab',
				'in_left'            => '1',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'VUV',
				'name'               => 'Vanuatu Vatu',
				'html_entity'        => '&#86;&#84;',
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'WST',
				'name'               => 'Samoa Tala',
				'html_entity'        => '&#87;&#83;&#36;',
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'XAF',
				'name'               => 'Communauté Financière Africaine (BEAC) CFA Franc B',
				'html_entity'        => '&#70;&#67;&#70;&#65;',
				'font_arial'         => 'F',
				'font_code2000'      => 'F',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'XCD',
				'name'               => 'East Caribbean Dollar',
				'html_entity'        => '&#36;',
				'font_arial'         => '$',
				'font_code2000'      => '$',
				'unicode_decimal'    => '36',
				'unicode_hex'        => '24',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'XDR',
				'name'               => 'International Monetary Fund (IMF) Special Drawing ',
				'html_entity'        => '',
				'font_arial'         => null,
				'font_code2000'      => null,
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'XOF',
				'name'               => 'Communauté Financière Africaine (BCEAO) Franc',
				'html_entity'        => '&#70;&#67;&#70;&#65;',
				'font_arial'         => 'F',
				'font_code2000'      => 'F',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'XPF',
				'name'               => 'Comptoirs Français du Pacifique (CFP) Franc',
				'html_entity'        => '&#70;',
				'font_arial'         => 'F',
				'font_code2000'      => 'F',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '0',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'YER',
				'name'               => 'Yemen Rial',
				'html_entity'        => '&#65020;',
				'font_arial'         => '﷼',
				'font_code2000'      => '﷼',
				'unicode_decimal'    => '65020',
				'unicode_hex'        => 'fdfc',
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'ZAR',
				'name'               => 'South Africa Rand',
				'html_entity'        => '&#82;',
				'font_arial'         => 'R',
				'font_code2000'      => 'R',
				'unicode_decimal'    => '82',
				'unicode_hex'        => '52',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'ZMW',
				'name'               => 'Zambia Kwacha',
				'html_entity'        => null,
				'font_arial'         => 'ZK',
				'font_code2000'      => 'ZK',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '0',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'ZWD',
				'name'               => 'Zimbabwe Dollar',
				'html_entity'        => null,
				'font_arial'         => 'Z$',
				'font_code2000'      => 'Z$',
				'unicode_decimal'    => '90, 3',
				'unicode_hex'        => '5a, 2',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'ZWL',
				'name'               => 'Zimbabwe Dollar',
				'html_entity'        => null,
				'font_arial'         => 'Z$',
				'font_code2000'      => 'Z$',
				'unicode_decimal'    => '90, 3',
				'unicode_hex'        => '5a, 2',
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
			[
				'code'               => 'XBT',
				'name'               => 'Bitcoin',
				'html_entity'        => '฿',
				'font_arial'         => '฿',
				'font_code2000'      => '฿',
				'unicode_decimal'    => null,
				'unicode_hex'        => null,
				'in_left'            => '1',
				'decimal_places'     => '2',
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => now()->format('Y-m-d H:i:s'),
				'updated_at'         => now()->format('Y-m-d H:i:s'),
			],
		];
		
		foreach ($entries as $entry) {
			DB::table('currencies')->insert($entry);
		}
	}
}
