<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TimeZoneSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$entries = [
			[
				'country_code' => 'CI',
				'time_zone_id' => 'Africa/Abidjan',
				'gmt'          => '0',
				'dst'          => '0',
				'raw'          => '0',
			],
			[
				'country_code' => 'GH',
				'time_zone_id' => 'Africa/Accra',
				'gmt'          => '0',
				'dst'          => '0',
				'raw'          => '0',
			],
			[
				'country_code' => 'ET',
				'time_zone_id' => 'Africa/Addis_Ababa',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'DZ',
				'time_zone_id' => 'Africa/Algiers',
				'gmt'          => '1',
				'dst'          => '1',
				'raw'          => '1',
			],
			[
				'country_code' => 'ER',
				'time_zone_id' => 'Africa/Asmara',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'ML',
				'time_zone_id' => 'Africa/Bamako',
				'gmt'          => '0',
				'dst'          => '0',
				'raw'          => '0',
			],
			[
				'country_code' => 'CF',
				'time_zone_id' => 'Africa/Bangui',
				'gmt'          => '1',
				'dst'          => '1',
				'raw'          => '1',
			],
			[
				'country_code' => 'GM',
				'time_zone_id' => 'Africa/Banjul',
				'gmt'          => '0',
				'dst'          => '0',
				'raw'          => '0',
			],
			[
				'country_code' => 'GW',
				'time_zone_id' => 'Africa/Bissau',
				'gmt'          => '0',
				'dst'          => '0',
				'raw'          => '0',
			],
			[
				'country_code' => 'MW',
				'time_zone_id' => 'Africa/Blantyre',
				'gmt'          => '2',
				'dst'          => '2',
				'raw'          => '2',
			],
			[
				'country_code' => 'CG',
				'time_zone_id' => 'Africa/Brazzaville',
				'gmt'          => '1',
				'dst'          => '1',
				'raw'          => '1',
			],
			[
				'country_code' => 'BI',
				'time_zone_id' => 'Africa/Bujumbura',
				'gmt'          => '2',
				'dst'          => '2',
				'raw'          => '2',
			],
			[
				'country_code' => 'EG',
				'time_zone_id' => 'Africa/Cairo',
				'gmt'          => '2',
				'dst'          => '2',
				'raw'          => '2',
			],
			[
				'country_code' => 'MA',
				'time_zone_id' => 'Africa/Casablanca',
				'gmt'          => '0',
				'dst'          => '1',
				'raw'          => '0',
			],
			[
				'country_code' => 'ES',
				'time_zone_id' => 'Africa/Ceuta',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'GN',
				'time_zone_id' => 'Africa/Conakry',
				'gmt'          => '0',
				'dst'          => '0',
				'raw'          => '0',
			],
			[
				'country_code' => 'SN',
				'time_zone_id' => 'Africa/Dakar',
				'gmt'          => '0',
				'dst'          => '0',
				'raw'          => '0',
			],
			[
				'country_code' => 'TZ',
				'time_zone_id' => 'Africa/Dar_es_Salaam',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'DJ',
				'time_zone_id' => 'Africa/Djibouti',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'CM',
				'time_zone_id' => 'Africa/Douala',
				'gmt'          => '1',
				'dst'          => '1',
				'raw'          => '1',
			],
			[
				'country_code' => 'EH',
				'time_zone_id' => 'Africa/El_Aaiun',
				'gmt'          => '0',
				'dst'          => '1',
				'raw'          => '0',
			],
			[
				'country_code' => 'SL',
				'time_zone_id' => 'Africa/Freetown',
				'gmt'          => '0',
				'dst'          => '0',
				'raw'          => '0',
			],
			[
				'country_code' => 'BW',
				'time_zone_id' => 'Africa/Gaborone',
				'gmt'          => '2',
				'dst'          => '2',
				'raw'          => '2',
			],
			[
				'country_code' => 'ZW',
				'time_zone_id' => 'Africa/Harare',
				'gmt'          => '2',
				'dst'          => '2',
				'raw'          => '2',
			],
			[
				'country_code' => 'ZA',
				'time_zone_id' => 'Africa/Johannesburg',
				'gmt'          => '2',
				'dst'          => '2',
				'raw'          => '2',
			],
			[
				'country_code' => 'SS',
				'time_zone_id' => 'Africa/Juba',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'UG',
				'time_zone_id' => 'Africa/Kampala',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'SD',
				'time_zone_id' => 'Africa/Khartoum',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'RW',
				'time_zone_id' => 'Africa/Kigali',
				'gmt'          => '2',
				'dst'          => '2',
				'raw'          => '2',
			],
			[
				'country_code' => 'CD',
				'time_zone_id' => 'Africa/Kinshasa',
				'gmt'          => '1',
				'dst'          => '1',
				'raw'          => '1',
			],
			[
				'country_code' => 'NG',
				'time_zone_id' => 'Africa/Lagos',
				'gmt'          => '1',
				'dst'          => '1',
				'raw'          => '1',
			],
			[
				'country_code' => 'GA',
				'time_zone_id' => 'Africa/Libreville',
				'gmt'          => '1',
				'dst'          => '1',
				'raw'          => '1',
			],
			[
				'country_code' => 'TG',
				'time_zone_id' => 'Africa/Lome',
				'gmt'          => '0',
				'dst'          => '0',
				'raw'          => '0',
			],
			[
				'country_code' => 'AO',
				'time_zone_id' => 'Africa/Luanda',
				'gmt'          => '1',
				'dst'          => '1',
				'raw'          => '1',
			],
			[
				'country_code' => 'CD',
				'time_zone_id' => 'Africa/Lubumbashi',
				'gmt'          => '2',
				'dst'          => '2',
				'raw'          => '2',
			],
			[
				'country_code' => 'ZM',
				'time_zone_id' => 'Africa/Lusaka',
				'gmt'          => '2',
				'dst'          => '2',
				'raw'          => '2',
			],
			[
				'country_code' => 'GQ',
				'time_zone_id' => 'Africa/Malabo',
				'gmt'          => '1',
				'dst'          => '1',
				'raw'          => '1',
			],
			[
				'country_code' => 'MZ',
				'time_zone_id' => 'Africa/Maputo',
				'gmt'          => '2',
				'dst'          => '2',
				'raw'          => '2',
			],
			[
				'country_code' => 'LS',
				'time_zone_id' => 'Africa/Maseru',
				'gmt'          => '2',
				'dst'          => '2',
				'raw'          => '2',
			],
			[
				'country_code' => 'SZ',
				'time_zone_id' => 'Africa/Mbabane',
				'gmt'          => '2',
				'dst'          => '2',
				'raw'          => '2',
			],
			[
				'country_code' => 'SO',
				'time_zone_id' => 'Africa/Mogadishu',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'LR',
				'time_zone_id' => 'Africa/Monrovia',
				'gmt'          => '0',
				'dst'          => '0',
				'raw'          => '0',
			],
			[
				'country_code' => 'KE',
				'time_zone_id' => 'Africa/Nairobi',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'TD',
				'time_zone_id' => 'Africa/Ndjamena',
				'gmt'          => '1',
				'dst'          => '1',
				'raw'          => '1',
			],
			[
				'country_code' => 'NE',
				'time_zone_id' => 'Africa/Niamey',
				'gmt'          => '1',
				'dst'          => '1',
				'raw'          => '1',
			],
			[
				'country_code' => 'MR',
				'time_zone_id' => 'Africa/Nouakchott',
				'gmt'          => '0',
				'dst'          => '0',
				'raw'          => '0',
			],
			[
				'country_code' => 'BF',
				'time_zone_id' => 'Africa/Ouagadougou',
				'gmt'          => '0',
				'dst'          => '0',
				'raw'          => '0',
			],
			[
				'country_code' => 'BJ',
				'time_zone_id' => 'Africa/Porto-Novo',
				'gmt'          => '1',
				'dst'          => '1',
				'raw'          => '1',
			],
			[
				'country_code' => 'ST',
				'time_zone_id' => 'Africa/Sao_Tome',
				'gmt'          => '0',
				'dst'          => '0',
				'raw'          => '0',
			],
			[
				'country_code' => 'LY',
				'time_zone_id' => 'Africa/Tripoli',
				'gmt'          => '2',
				'dst'          => '2',
				'raw'          => '2',
			],
			[
				'country_code' => 'TN',
				'time_zone_id' => 'Africa/Tunis',
				'gmt'          => '1',
				'dst'          => '1',
				'raw'          => '1',
			],
			[
				'country_code' => 'NA',
				'time_zone_id' => 'Africa/Windhoek',
				'gmt'          => '2',
				'dst'          => '1',
				'raw'          => '1',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Adak',
				'gmt'          => '-10',
				'dst'          => '-9',
				'raw'          => '-10',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Anchorage',
				'gmt'          => '-9',
				'dst'          => '-8',
				'raw'          => '-9',
			],
			[
				'country_code' => 'AI',
				'time_zone_id' => 'America/Anguilla',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'AG',
				'time_zone_id' => 'America/Antigua',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'BR',
				'time_zone_id' => 'America/Araguaina',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'AR',
				'time_zone_id' => 'America/Argentina/Buenos_Aires',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'AR',
				'time_zone_id' => 'America/Argentina/Catamarca',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'AR',
				'time_zone_id' => 'America/Argentina/Cordoba',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'AR',
				'time_zone_id' => 'America/Argentina/Jujuy',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'AR',
				'time_zone_id' => 'America/Argentina/La_Rioja',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'AR',
				'time_zone_id' => 'America/Argentina/Mendoza',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'AR',
				'time_zone_id' => 'America/Argentina/Rio_Gallegos',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'AR',
				'time_zone_id' => 'America/Argentina/Salta',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'AR',
				'time_zone_id' => 'America/Argentina/San_Juan',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'AR',
				'time_zone_id' => 'America/Argentina/San_Luis',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'AR',
				'time_zone_id' => 'America/Argentina/Tucuman',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'AR',
				'time_zone_id' => 'America/Argentina/Ushuaia',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'AW',
				'time_zone_id' => 'America/Aruba',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'PY',
				'time_zone_id' => 'America/Asuncion',
				'gmt'          => '-3',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Atikokan',
				'gmt'          => '-5',
				'dst'          => '-5',
				'raw'          => '-5',
			],
			[
				'country_code' => 'BR',
				'time_zone_id' => 'America/Bahia',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'MX',
				'time_zone_id' => 'America/Bahia_Banderas',
				'gmt'          => '-6',
				'dst'          => '-5',
				'raw'          => '-6',
			],
			[
				'country_code' => 'BB',
				'time_zone_id' => 'America/Barbados',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'BR',
				'time_zone_id' => 'America/Belem',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'BZ',
				'time_zone_id' => 'America/Belize',
				'gmt'          => '-6',
				'dst'          => '-6',
				'raw'          => '-6',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Blanc-Sablon',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'BR',
				'time_zone_id' => 'America/Boa_Vista',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'CO',
				'time_zone_id' => 'America/Bogota',
				'gmt'          => '-5',
				'dst'          => '-5',
				'raw'          => '-5',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Boise',
				'gmt'          => '-7',
				'dst'          => '-6',
				'raw'          => '-7',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Cambridge_Bay',
				'gmt'          => '-7',
				'dst'          => '-6',
				'raw'          => '-7',
			],
			[
				'country_code' => 'BR',
				'time_zone_id' => 'America/Campo_Grande',
				'gmt'          => '-3',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'MX',
				'time_zone_id' => 'America/Cancun',
				'gmt'          => '-5',
				'dst'          => '-5',
				'raw'          => '-5',
			],
			[
				'country_code' => 'VE',
				'time_zone_id' => 'America/Caracas',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'GF',
				'time_zone_id' => 'America/Cayenne',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'KY',
				'time_zone_id' => 'America/Cayman',
				'gmt'          => '-5',
				'dst'          => '-5',
				'raw'          => '-5',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Chicago',
				'gmt'          => '-6',
				'dst'          => '-5',
				'raw'          => '-6',
			],
			[
				'country_code' => 'MX',
				'time_zone_id' => 'America/Chihuahua',
				'gmt'          => '-7',
				'dst'          => '-6',
				'raw'          => '-7',
			],
			[
				'country_code' => 'CR',
				'time_zone_id' => 'America/Costa_Rica',
				'gmt'          => '-6',
				'dst'          => '-6',
				'raw'          => '-6',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Creston',
				'gmt'          => '-7',
				'dst'          => '-7',
				'raw'          => '-7',
			],
			[
				'country_code' => 'BR',
				'time_zone_id' => 'America/Cuiaba',
				'gmt'          => '-3',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'CW',
				'time_zone_id' => 'America/Curacao',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'GL',
				'time_zone_id' => 'America/Danmarkshavn',
				'gmt'          => '0',
				'dst'          => '0',
				'raw'          => '0',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Dawson',
				'gmt'          => '-8',
				'dst'          => '-7',
				'raw'          => '-8',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Dawson_Creek',
				'gmt'          => '-7',
				'dst'          => '-7',
				'raw'          => '-7',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Denver',
				'gmt'          => '-7',
				'dst'          => '-6',
				'raw'          => '-7',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Detroit',
				'gmt'          => '-5',
				'dst'          => '-4',
				'raw'          => '-5',
			],
			[
				'country_code' => 'DM',
				'time_zone_id' => 'America/Dominica',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Edmonton',
				'gmt'          => '-7',
				'dst'          => '-6',
				'raw'          => '-7',
			],
			[
				'country_code' => 'BR',
				'time_zone_id' => 'America/Eirunepe',
				'gmt'          => '-5',
				'dst'          => '-5',
				'raw'          => '-5',
			],
			[
				'country_code' => 'SV',
				'time_zone_id' => 'America/El_Salvador',
				'gmt'          => '-6',
				'dst'          => '-6',
				'raw'          => '-6',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Fort_Nelson',
				'gmt'          => '-7',
				'dst'          => '-7',
				'raw'          => '-7',
			],
			[
				'country_code' => 'BR',
				'time_zone_id' => 'America/Fortaleza',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Glace_Bay',
				'gmt'          => '-4',
				'dst'          => '-3',
				'raw'          => '-4',
			],
			[
				'country_code' => 'GL',
				'time_zone_id' => 'America/Godthab',
				'gmt'          => '-3',
				'dst'          => '-2',
				'raw'          => '-3',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Goose_Bay',
				'gmt'          => '-4',
				'dst'          => '-3',
				'raw'          => '-4',
			],
			[
				'country_code' => 'TC',
				'time_zone_id' => 'America/Grand_Turk',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'GD',
				'time_zone_id' => 'America/Grenada',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'GP',
				'time_zone_id' => 'America/Guadeloupe',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'GT',
				'time_zone_id' => 'America/Guatemala',
				'gmt'          => '-6',
				'dst'          => '-6',
				'raw'          => '-6',
			],
			[
				'country_code' => 'EC',
				'time_zone_id' => 'America/Guayaquil',
				'gmt'          => '-5',
				'dst'          => '-5',
				'raw'          => '-5',
			],
			[
				'country_code' => 'GY',
				'time_zone_id' => 'America/Guyana',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Halifax',
				'gmt'          => '-4',
				'dst'          => '-3',
				'raw'          => '-4',
			],
			[
				'country_code' => 'CU',
				'time_zone_id' => 'America/Havana',
				'gmt'          => '-5',
				'dst'          => '-4',
				'raw'          => '-5',
			],
			[
				'country_code' => 'MX',
				'time_zone_id' => 'America/Hermosillo',
				'gmt'          => '-7',
				'dst'          => '-7',
				'raw'          => '-7',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Indiana/Indianapolis',
				'gmt'          => '-5',
				'dst'          => '-4',
				'raw'          => '-5',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Indiana/Knox',
				'gmt'          => '-6',
				'dst'          => '-5',
				'raw'          => '-6',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Indiana/Marengo',
				'gmt'          => '-5',
				'dst'          => '-4',
				'raw'          => '-5',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Indiana/Petersburg',
				'gmt'          => '-5',
				'dst'          => '-4',
				'raw'          => '-5',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Indiana/Tell_City',
				'gmt'          => '-6',
				'dst'          => '-5',
				'raw'          => '-6',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Indiana/Vevay',
				'gmt'          => '-5',
				'dst'          => '-4',
				'raw'          => '-5',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Indiana/Vincennes',
				'gmt'          => '-5',
				'dst'          => '-4',
				'raw'          => '-5',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Indiana/Winamac',
				'gmt'          => '-5',
				'dst'          => '-4',
				'raw'          => '-5',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Inuvik',
				'gmt'          => '-7',
				'dst'          => '-6',
				'raw'          => '-7',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Iqaluit',
				'gmt'          => '-5',
				'dst'          => '-4',
				'raw'          => '-5',
			],
			[
				'country_code' => 'JM',
				'time_zone_id' => 'America/Jamaica',
				'gmt'          => '-5',
				'dst'          => '-5',
				'raw'          => '-5',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Juneau',
				'gmt'          => '-9',
				'dst'          => '-8',
				'raw'          => '-9',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Kentucky/Louisville',
				'gmt'          => '-5',
				'dst'          => '-4',
				'raw'          => '-5',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Kentucky/Monticello',
				'gmt'          => '-5',
				'dst'          => '-4',
				'raw'          => '-5',
			],
			[
				'country_code' => 'BQ',
				'time_zone_id' => 'America/Kralendijk',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'BO',
				'time_zone_id' => 'America/La_Paz',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'PE',
				'time_zone_id' => 'America/Lima',
				'gmt'          => '-5',
				'dst'          => '-5',
				'raw'          => '-5',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Los_Angeles',
				'gmt'          => '-8',
				'dst'          => '-7',
				'raw'          => '-8',
			],
			[
				'country_code' => 'SX',
				'time_zone_id' => 'America/Lower_Princes',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'BR',
				'time_zone_id' => 'America/Maceio',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'NI',
				'time_zone_id' => 'America/Managua',
				'gmt'          => '-6',
				'dst'          => '-6',
				'raw'          => '-6',
			],
			[
				'country_code' => 'BR',
				'time_zone_id' => 'America/Manaus',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'MF',
				'time_zone_id' => 'America/Marigot',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'MQ',
				'time_zone_id' => 'America/Martinique',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'MX',
				'time_zone_id' => 'America/Matamoros',
				'gmt'          => '-6',
				'dst'          => '-5',
				'raw'          => '-6',
			],
			[
				'country_code' => 'MX',
				'time_zone_id' => 'America/Mazatlan',
				'gmt'          => '-7',
				'dst'          => '-6',
				'raw'          => '-7',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Menominee',
				'gmt'          => '-6',
				'dst'          => '-5',
				'raw'          => '-6',
			],
			[
				'country_code' => 'MX',
				'time_zone_id' => 'America/Merida',
				'gmt'          => '-6',
				'dst'          => '-5',
				'raw'          => '-6',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Metlakatla',
				'gmt'          => '-9',
				'dst'          => '-8',
				'raw'          => '-9',
			],
			[
				'country_code' => 'MX',
				'time_zone_id' => 'America/Mexico_City',
				'gmt'          => '-6',
				'dst'          => '-5',
				'raw'          => '-6',
			],
			[
				'country_code' => 'PM',
				'time_zone_id' => 'America/Miquelon',
				'gmt'          => '-3',
				'dst'          => '-2',
				'raw'          => '-3',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Moncton',
				'gmt'          => '-4',
				'dst'          => '-3',
				'raw'          => '-4',
			],
			[
				'country_code' => 'MX',
				'time_zone_id' => 'America/Monterrey',
				'gmt'          => '-6',
				'dst'          => '-5',
				'raw'          => '-6',
			],
			[
				'country_code' => 'UY',
				'time_zone_id' => 'America/Montevideo',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'MS',
				'time_zone_id' => 'America/Montserrat',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'BS',
				'time_zone_id' => 'America/Nassau',
				'gmt'          => '-5',
				'dst'          => '-4',
				'raw'          => '-5',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/New_York',
				'gmt'          => '-5',
				'dst'          => '-4',
				'raw'          => '-5',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Nipigon',
				'gmt'          => '-5',
				'dst'          => '-4',
				'raw'          => '-5',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Nome',
				'gmt'          => '-9',
				'dst'          => '-8',
				'raw'          => '-9',
			],
			[
				'country_code' => 'BR',
				'time_zone_id' => 'America/Noronha',
				'gmt'          => '-2',
				'dst'          => '-2',
				'raw'          => '-2',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/North_Dakota/Beulah',
				'gmt'          => '-6',
				'dst'          => '-5',
				'raw'          => '-6',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/North_Dakota/Center',
				'gmt'          => '-6',
				'dst'          => '-5',
				'raw'          => '-6',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/North_Dakota/New_Salem',
				'gmt'          => '-6',
				'dst'          => '-5',
				'raw'          => '-6',
			],
			[
				'country_code' => 'MX',
				'time_zone_id' => 'America/Ojinaga',
				'gmt'          => '-7',
				'dst'          => '-6',
				'raw'          => '-7',
			],
			[
				'country_code' => 'PA',
				'time_zone_id' => 'America/Panama',
				'gmt'          => '-5',
				'dst'          => '-5',
				'raw'          => '-5',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Pangnirtung',
				'gmt'          => '-5',
				'dst'          => '-4',
				'raw'          => '-5',
			],
			[
				'country_code' => 'SR',
				'time_zone_id' => 'America/Paramaribo',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Phoenix',
				'gmt'          => '-7',
				'dst'          => '-7',
				'raw'          => '-7',
			],
			[
				'country_code' => 'HT',
				'time_zone_id' => 'America/Port-au-Prince',
				'gmt'          => '-5',
				'dst'          => '-4',
				'raw'          => '-5',
			],
			[
				'country_code' => 'TT',
				'time_zone_id' => 'America/Port_of_Spain',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'BR',
				'time_zone_id' => 'America/Porto_Velho',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'PR',
				'time_zone_id' => 'America/Puerto_Rico',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'CL',
				'time_zone_id' => 'America/Punta_Arenas',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Rainy_River',
				'gmt'          => '-6',
				'dst'          => '-5',
				'raw'          => '-6',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Rankin_Inlet',
				'gmt'          => '-6',
				'dst'          => '-5',
				'raw'          => '-6',
			],
			[
				'country_code' => 'BR',
				'time_zone_id' => 'America/Recife',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Regina',
				'gmt'          => '-6',
				'dst'          => '-6',
				'raw'          => '-6',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Resolute',
				'gmt'          => '-6',
				'dst'          => '-5',
				'raw'          => '-6',
			],
			[
				'country_code' => 'BR',
				'time_zone_id' => 'America/Rio_Branco',
				'gmt'          => '-5',
				'dst'          => '-5',
				'raw'          => '-5',
			],
			[
				'country_code' => 'BR',
				'time_zone_id' => 'America/Santarem',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'CL',
				'time_zone_id' => 'America/Santiago',
				'gmt'          => '-3',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'DO',
				'time_zone_id' => 'America/Santo_Domingo',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'BR',
				'time_zone_id' => 'America/Sao_Paulo',
				'gmt'          => '-2',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'GL',
				'time_zone_id' => 'America/Scoresbysund',
				'gmt'          => '-1',
				'dst'          => '0',
				'raw'          => '-1',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Sitka',
				'gmt'          => '-9',
				'dst'          => '-8',
				'raw'          => '-9',
			],
			[
				'country_code' => 'BL',
				'time_zone_id' => 'America/St_Barthelemy',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/St_Johns',
				'gmt'          => '-3.5',
				'dst'          => '-2.5',
				'raw'          => '-3.5',
			],
			[
				'country_code' => 'KN',
				'time_zone_id' => 'America/St_Kitts',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'LC',
				'time_zone_id' => 'America/St_Lucia',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'VI',
				'time_zone_id' => 'America/St_Thomas',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'VC',
				'time_zone_id' => 'America/St_Vincent',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Swift_Current',
				'gmt'          => '-6',
				'dst'          => '-6',
				'raw'          => '-6',
			],
			[
				'country_code' => 'HN',
				'time_zone_id' => 'America/Tegucigalpa',
				'gmt'          => '-6',
				'dst'          => '-6',
				'raw'          => '-6',
			],
			[
				'country_code' => 'GL',
				'time_zone_id' => 'America/Thule',
				'gmt'          => '-4',
				'dst'          => '-3',
				'raw'          => '-4',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Thunder_Bay',
				'gmt'          => '-5',
				'dst'          => '-4',
				'raw'          => '-5',
			],
			[
				'country_code' => 'MX',
				'time_zone_id' => 'America/Tijuana',
				'gmt'          => '-8',
				'dst'          => '-7',
				'raw'          => '-8',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Toronto',
				'gmt'          => '-5',
				'dst'          => '-4',
				'raw'          => '-5',
			],
			[
				'country_code' => 'VG',
				'time_zone_id' => 'America/Tortola',
				'gmt'          => '-4',
				'dst'          => '-4',
				'raw'          => '-4',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Vancouver',
				'gmt'          => '-8',
				'dst'          => '-7',
				'raw'          => '-8',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Whitehorse',
				'gmt'          => '-8',
				'dst'          => '-7',
				'raw'          => '-8',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Winnipeg',
				'gmt'          => '-6',
				'dst'          => '-5',
				'raw'          => '-6',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'America/Yakutat',
				'gmt'          => '-9',
				'dst'          => '-8',
				'raw'          => '-9',
			],
			[
				'country_code' => 'CA',
				'time_zone_id' => 'America/Yellowknife',
				'gmt'          => '-7',
				'dst'          => '-6',
				'raw'          => '-7',
			],
			[
				'country_code' => 'AQ',
				'time_zone_id' => 'Antarctica/Casey',
				'gmt'          => '11',
				'dst'          => '11',
				'raw'          => '11',
			],
			[
				'country_code' => 'AQ',
				'time_zone_id' => 'Antarctica/Davis',
				'gmt'          => '7',
				'dst'          => '7',
				'raw'          => '7',
			],
			[
				'country_code' => 'AQ',
				'time_zone_id' => 'Antarctica/DumontDUrville',
				'gmt'          => '10',
				'dst'          => '10',
				'raw'          => '10',
			],
			[
				'country_code' => 'AU',
				'time_zone_id' => 'Antarctica/Macquarie',
				'gmt'          => '11',
				'dst'          => '11',
				'raw'          => '11',
			],
			[
				'country_code' => 'AQ',
				'time_zone_id' => 'Antarctica/Mawson',
				'gmt'          => '5',
				'dst'          => '5',
				'raw'          => '5',
			],
			[
				'country_code' => 'AQ',
				'time_zone_id' => 'Antarctica/McMurdo',
				'gmt'          => '13',
				'dst'          => '12',
				'raw'          => '12',
			],
			[
				'country_code' => 'AQ',
				'time_zone_id' => 'Antarctica/Palmer',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'AQ',
				'time_zone_id' => 'Antarctica/Rothera',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'AQ',
				'time_zone_id' => 'Antarctica/Syowa',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'AQ',
				'time_zone_id' => 'Antarctica/Troll',
				'gmt'          => '0',
				'dst'          => '2',
				'raw'          => '0',
			],
			[
				'country_code' => 'AQ',
				'time_zone_id' => 'Antarctica/Vostok',
				'gmt'          => '6',
				'dst'          => '6',
				'raw'          => '6',
			],
			[
				'country_code' => 'SJ',
				'time_zone_id' => 'Arctic/Longyearbyen',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'YE',
				'time_zone_id' => 'Asia/Aden',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'KZ',
				'time_zone_id' => 'Asia/Almaty',
				'gmt'          => '6',
				'dst'          => '6',
				'raw'          => '6',
			],
			[
				'country_code' => 'JO',
				'time_zone_id' => 'Asia/Amman',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Asia/Anadyr',
				'gmt'          => '12',
				'dst'          => '12',
				'raw'          => '12',
			],
			[
				'country_code' => 'KZ',
				'time_zone_id' => 'Asia/Aqtau',
				'gmt'          => '5',
				'dst'          => '5',
				'raw'          => '5',
			],
			[
				'country_code' => 'KZ',
				'time_zone_id' => 'Asia/Aqtobe',
				'gmt'          => '5',
				'dst'          => '5',
				'raw'          => '5',
			],
			[
				'country_code' => 'TM',
				'time_zone_id' => 'Asia/Ashgabat',
				'gmt'          => '5',
				'dst'          => '5',
				'raw'          => '5',
			],
			[
				'country_code' => 'KZ',
				'time_zone_id' => 'Asia/Atyrau',
				'gmt'          => '5',
				'dst'          => '5',
				'raw'          => '5',
			],
			[
				'country_code' => 'IQ',
				'time_zone_id' => 'Asia/Baghdad',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'BH',
				'time_zone_id' => 'Asia/Bahrain',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'AZ',
				'time_zone_id' => 'Asia/Baku',
				'gmt'          => '4',
				'dst'          => '4',
				'raw'          => '4',
			],
			[
				'country_code' => 'TH',
				'time_zone_id' => 'Asia/Bangkok',
				'gmt'          => '7',
				'dst'          => '7',
				'raw'          => '7',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Asia/Barnaul',
				'gmt'          => '7',
				'dst'          => '7',
				'raw'          => '7',
			],
			[
				'country_code' => 'LB',
				'time_zone_id' => 'Asia/Beirut',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'KG',
				'time_zone_id' => 'Asia/Bishkek',
				'gmt'          => '6',
				'dst'          => '6',
				'raw'          => '6',
			],
			[
				'country_code' => 'BN',
				'time_zone_id' => 'Asia/Brunei',
				'gmt'          => '8',
				'dst'          => '8',
				'raw'          => '8',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Asia/Chita',
				'gmt'          => '9',
				'dst'          => '9',
				'raw'          => '9',
			],
			[
				'country_code' => 'MN',
				'time_zone_id' => 'Asia/Choibalsan',
				'gmt'          => '8',
				'dst'          => '8',
				'raw'          => '8',
			],
			[
				'country_code' => 'LK',
				'time_zone_id' => 'Asia/Colombo',
				'gmt'          => '5.5',
				'dst'          => '5.5',
				'raw'          => '5.5',
			],
			[
				'country_code' => 'SY',
				'time_zone_id' => 'Asia/Damascus',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'BD',
				'time_zone_id' => 'Asia/Dhaka',
				'gmt'          => '6',
				'dst'          => '6',
				'raw'          => '6',
			],
			[
				'country_code' => 'TL',
				'time_zone_id' => 'Asia/Dili',
				'gmt'          => '9',
				'dst'          => '9',
				'raw'          => '9',
			],
			[
				'country_code' => 'AE',
				'time_zone_id' => 'Asia/Dubai',
				'gmt'          => '4',
				'dst'          => '4',
				'raw'          => '4',
			],
			[
				'country_code' => 'TJ',
				'time_zone_id' => 'Asia/Dushanbe',
				'gmt'          => '5',
				'dst'          => '5',
				'raw'          => '5',
			],
			[
				'country_code' => 'CY',
				'time_zone_id' => 'Asia/Famagusta',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'PS',
				'time_zone_id' => 'Asia/Gaza',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'PS',
				'time_zone_id' => 'Asia/Hebron',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'VN',
				'time_zone_id' => 'Asia/Ho_Chi_Minh',
				'gmt'          => '7',
				'dst'          => '7',
				'raw'          => '7',
			],
			[
				'country_code' => 'HK',
				'time_zone_id' => 'Asia/Hong_Kong',
				'gmt'          => '8',
				'dst'          => '8',
				'raw'          => '8',
			],
			[
				'country_code' => 'MN',
				'time_zone_id' => 'Asia/Hovd',
				'gmt'          => '7',
				'dst'          => '7',
				'raw'          => '7',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Asia/Irkutsk',
				'gmt'          => '8',
				'dst'          => '8',
				'raw'          => '8',
			],
			[
				'country_code' => 'ID',
				'time_zone_id' => 'Asia/Jakarta',
				'gmt'          => '7',
				'dst'          => '7',
				'raw'          => '7',
			],
			[
				'country_code' => 'ID',
				'time_zone_id' => 'Asia/Jayapura',
				'gmt'          => '9',
				'dst'          => '9',
				'raw'          => '9',
			],
			[
				'country_code' => 'IL',
				'time_zone_id' => 'Asia/Jerusalem',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'AF',
				'time_zone_id' => 'Asia/Kabul',
				'gmt'          => '4.5',
				'dst'          => '4.5',
				'raw'          => '4.5',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Asia/Kamchatka',
				'gmt'          => '12',
				'dst'          => '12',
				'raw'          => '12',
			],
			[
				'country_code' => 'PK',
				'time_zone_id' => 'Asia/Karachi',
				'gmt'          => '5',
				'dst'          => '5',
				'raw'          => '5',
			],
			[
				'country_code' => 'NP',
				'time_zone_id' => 'Asia/Kathmandu',
				'gmt'          => '5.75',
				'dst'          => '5.75',
				'raw'          => '5.75',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Asia/Khandyga',
				'gmt'          => '9',
				'dst'          => '9',
				'raw'          => '9',
			],
			[
				'country_code' => 'IN',
				'time_zone_id' => 'Asia/Kolkata',
				'gmt'          => '5.5',
				'dst'          => '5.5',
				'raw'          => '5.5',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Asia/Krasnoyarsk',
				'gmt'          => '7',
				'dst'          => '7',
				'raw'          => '7',
			],
			[
				'country_code' => 'MY',
				'time_zone_id' => 'Asia/Kuala_Lumpur',
				'gmt'          => '8',
				'dst'          => '8',
				'raw'          => '8',
			],
			[
				'country_code' => 'MY',
				'time_zone_id' => 'Asia/Kuching',
				'gmt'          => '8',
				'dst'          => '8',
				'raw'          => '8',
			],
			[
				'country_code' => 'KW',
				'time_zone_id' => 'Asia/Kuwait',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'MO',
				'time_zone_id' => 'Asia/Macau',
				'gmt'          => '8',
				'dst'          => '8',
				'raw'          => '8',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Asia/Magadan',
				'gmt'          => '11',
				'dst'          => '11',
				'raw'          => '11',
			],
			[
				'country_code' => 'ID',
				'time_zone_id' => 'Asia/Makassar',
				'gmt'          => '8',
				'dst'          => '8',
				'raw'          => '8',
			],
			[
				'country_code' => 'PH',
				'time_zone_id' => 'Asia/Manila',
				'gmt'          => '8',
				'dst'          => '8',
				'raw'          => '8',
			],
			[
				'country_code' => 'OM',
				'time_zone_id' => 'Asia/Muscat',
				'gmt'          => '4',
				'dst'          => '4',
				'raw'          => '4',
			],
			[
				'country_code' => 'CY',
				'time_zone_id' => 'Asia/Nicosia',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Asia/Novokuznetsk',
				'gmt'          => '7',
				'dst'          => '7',
				'raw'          => '7',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Asia/Novosibirsk',
				'gmt'          => '7',
				'dst'          => '7',
				'raw'          => '7',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Asia/Omsk',
				'gmt'          => '6',
				'dst'          => '6',
				'raw'          => '6',
			],
			[
				'country_code' => 'KZ',
				'time_zone_id' => 'Asia/Oral',
				'gmt'          => '5',
				'dst'          => '5',
				'raw'          => '5',
			],
			[
				'country_code' => 'KH',
				'time_zone_id' => 'Asia/Phnom_Penh',
				'gmt'          => '7',
				'dst'          => '7',
				'raw'          => '7',
			],
			[
				'country_code' => 'ID',
				'time_zone_id' => 'Asia/Pontianak',
				'gmt'          => '7',
				'dst'          => '7',
				'raw'          => '7',
			],
			[
				'country_code' => 'KP',
				'time_zone_id' => 'Asia/Pyongyang',
				'gmt'          => '8.5',
				'dst'          => '8.5',
				'raw'          => '8.5',
			],
			[
				'country_code' => 'QA',
				'time_zone_id' => 'Asia/Qatar',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'KZ',
				'time_zone_id' => 'Asia/Qyzylorda',
				'gmt'          => '6',
				'dst'          => '6',
				'raw'          => '6',
			],
			[
				'country_code' => 'SA',
				'time_zone_id' => 'Asia/Riyadh',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Asia/Sakhalin',
				'gmt'          => '11',
				'dst'          => '11',
				'raw'          => '11',
			],
			[
				'country_code' => 'UZ',
				'time_zone_id' => 'Asia/Samarkand',
				'gmt'          => '5',
				'dst'          => '5',
				'raw'          => '5',
			],
			[
				'country_code' => 'KR',
				'time_zone_id' => 'Asia/Seoul',
				'gmt'          => '9',
				'dst'          => '9',
				'raw'          => '9',
			],
			[
				'country_code' => 'CN',
				'time_zone_id' => 'Asia/Shanghai',
				'gmt'          => '8',
				'dst'          => '8',
				'raw'          => '8',
			],
			[
				'country_code' => 'SG',
				'time_zone_id' => 'Asia/Singapore',
				'gmt'          => '8',
				'dst'          => '8',
				'raw'          => '8',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Asia/Srednekolymsk',
				'gmt'          => '11',
				'dst'          => '11',
				'raw'          => '11',
			],
			[
				'country_code' => 'TW',
				'time_zone_id' => 'Asia/Taipei',
				'gmt'          => '8',
				'dst'          => '8',
				'raw'          => '8',
			],
			[
				'country_code' => 'UZ',
				'time_zone_id' => 'Asia/Tashkent',
				'gmt'          => '5',
				'dst'          => '5',
				'raw'          => '5',
			],
			[
				'country_code' => 'GE',
				'time_zone_id' => 'Asia/Tbilisi',
				'gmt'          => '4',
				'dst'          => '4',
				'raw'          => '4',
			],
			[
				'country_code' => 'IR',
				'time_zone_id' => 'Asia/Tehran',
				'gmt'          => '3.5',
				'dst'          => '4.5',
				'raw'          => '3.5',
			],
			[
				'country_code' => 'BT',
				'time_zone_id' => 'Asia/Thimphu',
				'gmt'          => '6',
				'dst'          => '6',
				'raw'          => '6',
			],
			[
				'country_code' => 'JP',
				'time_zone_id' => 'Asia/Tokyo',
				'gmt'          => '9',
				'dst'          => '9',
				'raw'          => '9',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Asia/Tomsk',
				'gmt'          => '7',
				'dst'          => '7',
				'raw'          => '7',
			],
			[
				'country_code' => 'MN',
				'time_zone_id' => 'Asia/Ulaanbaatar',
				'gmt'          => '8',
				'dst'          => '8',
				'raw'          => '8',
			],
			[
				'country_code' => 'CN',
				'time_zone_id' => 'Asia/Urumqi',
				'gmt'          => '6',
				'dst'          => '6',
				'raw'          => '6',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Asia/Ust-Nera',
				'gmt'          => '10',
				'dst'          => '10',
				'raw'          => '10',
			],
			[
				'country_code' => 'LA',
				'time_zone_id' => 'Asia/Vientiane',
				'gmt'          => '7',
				'dst'          => '7',
				'raw'          => '7',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Asia/Vladivostok',
				'gmt'          => '10',
				'dst'          => '10',
				'raw'          => '10',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Asia/Yakutsk',
				'gmt'          => '9',
				'dst'          => '9',
				'raw'          => '9',
			],
			[
				'country_code' => 'MM',
				'time_zone_id' => 'Asia/Yangon',
				'gmt'          => '6.5',
				'dst'          => '6.5',
				'raw'          => '6.5',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Asia/Yekaterinburg',
				'gmt'          => '5',
				'dst'          => '5',
				'raw'          => '5',
			],
			[
				'country_code' => 'AM',
				'time_zone_id' => 'Asia/Yerevan',
				'gmt'          => '4',
				'dst'          => '4',
				'raw'          => '4',
			],
			[
				'country_code' => 'PT',
				'time_zone_id' => 'Atlantic/Azores',
				'gmt'          => '-1',
				'dst'          => '0',
				'raw'          => '-1',
			],
			[
				'country_code' => 'BM',
				'time_zone_id' => 'Atlantic/Bermuda',
				'gmt'          => '-4',
				'dst'          => '-3',
				'raw'          => '-4',
			],
			[
				'country_code' => 'ES',
				'time_zone_id' => 'Atlantic/Canary',
				'gmt'          => '0',
				'dst'          => '1',
				'raw'          => '0',
			],
			[
				'country_code' => 'CV',
				'time_zone_id' => 'Atlantic/Cape_Verde',
				'gmt'          => '-1',
				'dst'          => '-1',
				'raw'          => '-1',
			],
			[
				'country_code' => 'FO',
				'time_zone_id' => 'Atlantic/Faroe',
				'gmt'          => '0',
				'dst'          => '1',
				'raw'          => '0',
			],
			[
				'country_code' => 'PT',
				'time_zone_id' => 'Atlantic/Madeira',
				'gmt'          => '0',
				'dst'          => '1',
				'raw'          => '0',
			],
			[
				'country_code' => 'IS',
				'time_zone_id' => 'Atlantic/Reykjavik',
				'gmt'          => '0',
				'dst'          => '0',
				'raw'          => '0',
			],
			[
				'country_code' => 'GS',
				'time_zone_id' => 'Atlantic/South_Georgia',
				'gmt'          => '-2',
				'dst'          => '-2',
				'raw'          => '-2',
			],
			[
				'country_code' => 'SH',
				'time_zone_id' => 'Atlantic/St_Helena',
				'gmt'          => '0',
				'dst'          => '0',
				'raw'          => '0',
			],
			[
				'country_code' => 'FK',
				'time_zone_id' => 'Atlantic/Stanley',
				'gmt'          => '-3',
				'dst'          => '-3',
				'raw'          => '-3',
			],
			[
				'country_code' => 'AU',
				'time_zone_id' => 'Australia/Adelaide',
				'gmt'          => '10.5',
				'dst'          => '9.5',
				'raw'          => '9.5',
			],
			[
				'country_code' => 'AU',
				'time_zone_id' => 'Australia/Brisbane',
				'gmt'          => '10',
				'dst'          => '10',
				'raw'          => '10',
			],
			[
				'country_code' => 'AU',
				'time_zone_id' => 'Australia/Broken_Hill',
				'gmt'          => '10.5',
				'dst'          => '9.5',
				'raw'          => '9.5',
			],
			[
				'country_code' => 'AU',
				'time_zone_id' => 'Australia/Currie',
				'gmt'          => '11',
				'dst'          => '10',
				'raw'          => '10',
			],
			[
				'country_code' => 'AU',
				'time_zone_id' => 'Australia/Darwin',
				'gmt'          => '9.5',
				'dst'          => '9.5',
				'raw'          => '9.5',
			],
			[
				'country_code' => 'AU',
				'time_zone_id' => 'Australia/Eucla',
				'gmt'          => '8.75',
				'dst'          => '8.75',
				'raw'          => '8.75',
			],
			[
				'country_code' => 'AU',
				'time_zone_id' => 'Australia/Hobart',
				'gmt'          => '11',
				'dst'          => '10',
				'raw'          => '10',
			],
			[
				'country_code' => 'AU',
				'time_zone_id' => 'Australia/Lindeman',
				'gmt'          => '10',
				'dst'          => '10',
				'raw'          => '10',
			],
			[
				'country_code' => 'AU',
				'time_zone_id' => 'Australia/Lord_Howe',
				'gmt'          => '11',
				'dst'          => '10.5',
				'raw'          => '10.5',
			],
			[
				'country_code' => 'AU',
				'time_zone_id' => 'Australia/Melbourne',
				'gmt'          => '11',
				'dst'          => '10',
				'raw'          => '10',
			],
			[
				'country_code' => 'AU',
				'time_zone_id' => 'Australia/Perth',
				'gmt'          => '8',
				'dst'          => '8',
				'raw'          => '8',
			],
			[
				'country_code' => 'AU',
				'time_zone_id' => 'Australia/Sydney',
				'gmt'          => '11',
				'dst'          => '10',
				'raw'          => '10',
			],
			[
				'country_code' => 'NL',
				'time_zone_id' => 'Europe/Amsterdam',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'AD',
				'time_zone_id' => 'Europe/Andorra',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Europe/Astrakhan',
				'gmt'          => '4',
				'dst'          => '4',
				'raw'          => '4',
			],
			[
				'country_code' => 'GR',
				'time_zone_id' => 'Europe/Athens',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'RS',
				'time_zone_id' => 'Europe/Belgrade',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'DE',
				'time_zone_id' => 'Europe/Berlin',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'SK',
				'time_zone_id' => 'Europe/Bratislava',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'BE',
				'time_zone_id' => 'Europe/Brussels',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'RO',
				'time_zone_id' => 'Europe/Bucharest',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'HU',
				'time_zone_id' => 'Europe/Budapest',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'DE',
				'time_zone_id' => 'Europe/Busingen',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'MD',
				'time_zone_id' => 'Europe/Chisinau',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'DK',
				'time_zone_id' => 'Europe/Copenhagen',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'IE',
				'time_zone_id' => 'Europe/Dublin',
				'gmt'          => '0',
				'dst'          => '1',
				'raw'          => '0',
			],
			[
				'country_code' => 'GI',
				'time_zone_id' => 'Europe/Gibraltar',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'GG',
				'time_zone_id' => 'Europe/Guernsey',
				'gmt'          => '0',
				'dst'          => '1',
				'raw'          => '0',
			],
			[
				'country_code' => 'FI',
				'time_zone_id' => 'Europe/Helsinki',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'IM',
				'time_zone_id' => 'Europe/Isle_of_Man',
				'gmt'          => '0',
				'dst'          => '1',
				'raw'          => '0',
			],
			[
				'country_code' => 'TR',
				'time_zone_id' => 'Europe/Istanbul',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'JE',
				'time_zone_id' => 'Europe/Jersey',
				'gmt'          => '0',
				'dst'          => '1',
				'raw'          => '0',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Europe/Kaliningrad',
				'gmt'          => '2',
				'dst'          => '2',
				'raw'          => '2',
			],
			[
				'country_code' => 'UA',
				'time_zone_id' => 'Europe/Kiev',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Europe/Kirov',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'PT',
				'time_zone_id' => 'Europe/Lisbon',
				'gmt'          => '0',
				'dst'          => '1',
				'raw'          => '0',
			],
			[
				'country_code' => 'SI',
				'time_zone_id' => 'Europe/Ljubljana',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'UK',
				'time_zone_id' => 'Europe/London',
				'gmt'          => '0',
				'dst'          => '1',
				'raw'          => '0',
			],
			[
				'country_code' => 'LU',
				'time_zone_id' => 'Europe/Luxembourg',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'ES',
				'time_zone_id' => 'Europe/Madrid',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'MT',
				'time_zone_id' => 'Europe/Malta',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'AX',
				'time_zone_id' => 'Europe/Mariehamn',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'BY',
				'time_zone_id' => 'Europe/Minsk',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'MC',
				'time_zone_id' => 'Europe/Monaco',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Europe/Moscow',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'NO',
				'time_zone_id' => 'Europe/Oslo',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'FR',
				'time_zone_id' => 'Europe/Paris',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'ME',
				'time_zone_id' => 'Europe/Podgorica',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'CZ',
				'time_zone_id' => 'Europe/Prague',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'LV',
				'time_zone_id' => 'Europe/Riga',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'IT',
				'time_zone_id' => 'Europe/Rome',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Europe/Samara',
				'gmt'          => '4',
				'dst'          => '4',
				'raw'          => '4',
			],
			[
				'country_code' => 'SM',
				'time_zone_id' => 'Europe/San_Marino',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'BA',
				'time_zone_id' => 'Europe/Sarajevo',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Europe/Saratov',
				'gmt'          => '4',
				'dst'          => '4',
				'raw'          => '4',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Europe/Simferopol',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'MK',
				'time_zone_id' => 'Europe/Skopje',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'BG',
				'time_zone_id' => 'Europe/Sofia',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'SE',
				'time_zone_id' => 'Europe/Stockholm',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'EE',
				'time_zone_id' => 'Europe/Tallinn',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'AL',
				'time_zone_id' => 'Europe/Tirane',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Europe/Ulyanovsk',
				'gmt'          => '4',
				'dst'          => '4',
				'raw'          => '4',
			],
			[
				'country_code' => 'UA',
				'time_zone_id' => 'Europe/Uzhgorod',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'LI',
				'time_zone_id' => 'Europe/Vaduz',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'VA',
				'time_zone_id' => 'Europe/Vatican',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'AT',
				'time_zone_id' => 'Europe/Vienna',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'LT',
				'time_zone_id' => 'Europe/Vilnius',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'RU',
				'time_zone_id' => 'Europe/Volgograd',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'PL',
				'time_zone_id' => 'Europe/Warsaw',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'HR',
				'time_zone_id' => 'Europe/Zagreb',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'UA',
				'time_zone_id' => 'Europe/Zaporozhye',
				'gmt'          => '2',
				'dst'          => '3',
				'raw'          => '2',
			],
			[
				'country_code' => 'CH',
				'time_zone_id' => 'Europe/Zurich',
				'gmt'          => '1',
				'dst'          => '2',
				'raw'          => '1',
			],
			[
				'country_code' => 'MG',
				'time_zone_id' => 'Indian/Antananarivo',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'IO',
				'time_zone_id' => 'Indian/Chagos',
				'gmt'          => '6',
				'dst'          => '6',
				'raw'          => '6',
			],
			[
				'country_code' => 'CX',
				'time_zone_id' => 'Indian/Christmas',
				'gmt'          => '7',
				'dst'          => '7',
				'raw'          => '7',
			],
			[
				'country_code' => 'CC',
				'time_zone_id' => 'Indian/Cocos',
				'gmt'          => '6.5',
				'dst'          => '6.5',
				'raw'          => '6.5',
			],
			[
				'country_code' => 'KM',
				'time_zone_id' => 'Indian/Comoro',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'TF',
				'time_zone_id' => 'Indian/Kerguelen',
				'gmt'          => '5',
				'dst'          => '5',
				'raw'          => '5',
			],
			[
				'country_code' => 'SC',
				'time_zone_id' => 'Indian/Mahe',
				'gmt'          => '4',
				'dst'          => '4',
				'raw'          => '4',
			],
			[
				'country_code' => 'MV',
				'time_zone_id' => 'Indian/Maldives',
				'gmt'          => '5',
				'dst'          => '5',
				'raw'          => '5',
			],
			[
				'country_code' => 'MU',
				'time_zone_id' => 'Indian/Mauritius',
				'gmt'          => '4',
				'dst'          => '4',
				'raw'          => '4',
			],
			[
				'country_code' => 'YT',
				'time_zone_id' => 'Indian/Mayotte',
				'gmt'          => '3',
				'dst'          => '3',
				'raw'          => '3',
			],
			[
				'country_code' => 'RE',
				'time_zone_id' => 'Indian/Reunion',
				'gmt'          => '4',
				'dst'          => '4',
				'raw'          => '4',
			],
			[
				'country_code' => 'WS',
				'time_zone_id' => 'Pacific/Apia',
				'gmt'          => '14',
				'dst'          => '13',
				'raw'          => '13',
			],
			[
				'country_code' => 'NZ',
				'time_zone_id' => 'Pacific/Auckland',
				'gmt'          => '13',
				'dst'          => '12',
				'raw'          => '12',
			],
			[
				'country_code' => 'PG',
				'time_zone_id' => 'Pacific/Bougainville',
				'gmt'          => '11',
				'dst'          => '11',
				'raw'          => '11',
			],
			[
				'country_code' => 'NZ',
				'time_zone_id' => 'Pacific/Chatham',
				'gmt'          => '13.75',
				'dst'          => '12.75',
				'raw'          => '12.75',
			],
			[
				'country_code' => 'FM',
				'time_zone_id' => 'Pacific/Chuuk',
				'gmt'          => '10',
				'dst'          => '10',
				'raw'          => '10',
			],
			[
				'country_code' => 'CL',
				'time_zone_id' => 'Pacific/Easter',
				'gmt'          => '-5',
				'dst'          => '-6',
				'raw'          => '-6',
			],
			[
				'country_code' => 'VU',
				'time_zone_id' => 'Pacific/Efate',
				'gmt'          => '11',
				'dst'          => '11',
				'raw'          => '11',
			],
			[
				'country_code' => 'KI',
				'time_zone_id' => 'Pacific/Enderbury',
				'gmt'          => '13',
				'dst'          => '13',
				'raw'          => '13',
			],
			[
				'country_code' => 'TK',
				'time_zone_id' => 'Pacific/Fakaofo',
				'gmt'          => '13',
				'dst'          => '13',
				'raw'          => '13',
			],
			[
				'country_code' => 'FJ',
				'time_zone_id' => 'Pacific/Fiji',
				'gmt'          => '13',
				'dst'          => '12',
				'raw'          => '12',
			],
			[
				'country_code' => 'TV',
				'time_zone_id' => 'Pacific/Funafuti',
				'gmt'          => '12',
				'dst'          => '12',
				'raw'          => '12',
			],
			[
				'country_code' => 'EC',
				'time_zone_id' => 'Pacific/Galapagos',
				'gmt'          => '-6',
				'dst'          => '-6',
				'raw'          => '-6',
			],
			[
				'country_code' => 'PF',
				'time_zone_id' => 'Pacific/Gambier',
				'gmt'          => '-9',
				'dst'          => '-9',
				'raw'          => '-9',
			],
			[
				'country_code' => 'SB',
				'time_zone_id' => 'Pacific/Guadalcanal',
				'gmt'          => '11',
				'dst'          => '11',
				'raw'          => '11',
			],
			[
				'country_code' => 'GU',
				'time_zone_id' => 'Pacific/Guam',
				'gmt'          => '10',
				'dst'          => '10',
				'raw'          => '10',
			],
			[
				'country_code' => 'US',
				'time_zone_id' => 'Pacific/Honolulu',
				'gmt'          => '-10',
				'dst'          => '-10',
				'raw'          => '-10',
			],
			[
				'country_code' => 'KI',
				'time_zone_id' => 'Pacific/Kiritimati',
				'gmt'          => '14',
				'dst'          => '14',
				'raw'          => '14',
			],
			[
				'country_code' => 'FM',
				'time_zone_id' => 'Pacific/Kosrae',
				'gmt'          => '11',
				'dst'          => '11',
				'raw'          => '11',
			],
			[
				'country_code' => 'MH',
				'time_zone_id' => 'Pacific/Kwajalein',
				'gmt'          => '12',
				'dst'          => '12',
				'raw'          => '12',
			],
			[
				'country_code' => 'MH',
				'time_zone_id' => 'Pacific/Majuro',
				'gmt'          => '12',
				'dst'          => '12',
				'raw'          => '12',
			],
			[
				'country_code' => 'PF',
				'time_zone_id' => 'Pacific/Marquesas',
				'gmt'          => '-9.5',
				'dst'          => '-9.5',
				'raw'          => '-9.5',
			],
			[
				'country_code' => 'UM',
				'time_zone_id' => 'Pacific/Midway',
				'gmt'          => '-11',
				'dst'          => '-11',
				'raw'          => '-11',
			],
			[
				'country_code' => 'NR',
				'time_zone_id' => 'Pacific/Nauru',
				'gmt'          => '12',
				'dst'          => '12',
				'raw'          => '12',
			],
			[
				'country_code' => 'NU',
				'time_zone_id' => 'Pacific/Niue',
				'gmt'          => '-11',
				'dst'          => '-11',
				'raw'          => '-11',
			],
			[
				'country_code' => 'NF',
				'time_zone_id' => 'Pacific/Norfolk',
				'gmt'          => '11',
				'dst'          => '11',
				'raw'          => '11',
			],
			[
				'country_code' => 'NC',
				'time_zone_id' => 'Pacific/Noumea',
				'gmt'          => '11',
				'dst'          => '11',
				'raw'          => '11',
			],
			[
				'country_code' => 'AS',
				'time_zone_id' => 'Pacific/Pago_Pago',
				'gmt'          => '-11',
				'dst'          => '-11',
				'raw'          => '-11',
			],
			[
				'country_code' => 'PW',
				'time_zone_id' => 'Pacific/Palau',
				'gmt'          => '9',
				'dst'          => '9',
				'raw'          => '9',
			],
			[
				'country_code' => 'PN',
				'time_zone_id' => 'Pacific/Pitcairn',
				'gmt'          => '-8',
				'dst'          => '-8',
				'raw'          => '-8',
			],
			[
				'country_code' => 'FM',
				'time_zone_id' => 'Pacific/Pohnpei',
				'gmt'          => '11',
				'dst'          => '11',
				'raw'          => '11',
			],
			[
				'country_code' => 'PG',
				'time_zone_id' => 'Pacific/Port_Moresby',
				'gmt'          => '10',
				'dst'          => '10',
				'raw'          => '10',
			],
			[
				'country_code' => 'CK',
				'time_zone_id' => 'Pacific/Rarotonga',
				'gmt'          => '-10',
				'dst'          => '-10',
				'raw'          => '-10',
			],
			[
				'country_code' => 'MP',
				'time_zone_id' => 'Pacific/Saipan',
				'gmt'          => '10',
				'dst'          => '10',
				'raw'          => '10',
			],
			[
				'country_code' => 'PF',
				'time_zone_id' => 'Pacific/Tahiti',
				'gmt'          => '-10',
				'dst'          => '-10',
				'raw'          => '-10',
			],
			[
				'country_code' => 'KI',
				'time_zone_id' => 'Pacific/Tarawa',
				'gmt'          => '12',
				'dst'          => '12',
				'raw'          => '12',
			],
			[
				'country_code' => 'TO',
				'time_zone_id' => 'Pacific/Tongatapu',
				'gmt'          => '14',
				'dst'          => '13',
				'raw'          => '13',
			],
			[
				'country_code' => 'UM',
				'time_zone_id' => 'Pacific/Wake',
				'gmt'          => '12',
				'dst'          => '12',
				'raw'          => '12',
			],
			[
				'country_code' => 'WF',
				'time_zone_id' => 'Pacific/Wallis',
				'gmt'          => '12',
				'dst'          => '12',
				'raw'          => '12',
			],
		];
		
		foreach ($entries as $entry) {
			DB::table('time_zones')->insert($entry);
		}
	}
}
