-- MySQL dump 10.13  Distrib 5.7.26, for osx10.10 (x86_64)
--
-- Host: 127.0.0.1    Database: laraclassified
-- ------------------------------------------------------
-- Server version	5.7.26

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping data for table `<<prefix>>subadmin1`
--

/*!40000 ALTER TABLE `<<prefix>>subadmin1` DISABLE KEYS */;
INSERT INTO `<<prefix>>subadmin1` (`code`, `country_code`, `name`, `asciiname`, `active`) VALUES ('BO.09','BO','Tarija','Tarija',1);
INSERT INTO `<<prefix>>subadmin1` (`code`, `country_code`, `name`, `asciiname`, `active`) VALUES ('BO.08','BO','Santa Cruz','Santa Cruz',1);
INSERT INTO `<<prefix>>subadmin1` (`code`, `country_code`, `name`, `asciiname`, `active`) VALUES ('BO.07','BO','Potosí','Potosi',1);
INSERT INTO `<<prefix>>subadmin1` (`code`, `country_code`, `name`, `asciiname`, `active`) VALUES ('BO.06','BO','Pando','Pando',1);
INSERT INTO `<<prefix>>subadmin1` (`code`, `country_code`, `name`, `asciiname`, `active`) VALUES ('BO.05','BO','Oruro','Oruro',1);
INSERT INTO `<<prefix>>subadmin1` (`code`, `country_code`, `name`, `asciiname`, `active`) VALUES ('BO.04','BO','La Paz','La Paz',1);
INSERT INTO `<<prefix>>subadmin1` (`code`, `country_code`, `name`, `asciiname`, `active`) VALUES ('BO.02','BO','Cochabamba','Cochabamba',1);
INSERT INTO `<<prefix>>subadmin1` (`code`, `country_code`, `name`, `asciiname`, `active`) VALUES ('BO.01','BO','Chuquisaca','Chuquisaca',1);
INSERT INTO `<<prefix>>subadmin1` (`code`, `country_code`, `name`, `asciiname`, `active`) VALUES ('BO.03','BO','El Beni','El Beni',1);
/*!40000 ALTER TABLE `<<prefix>>subadmin1` ENABLE KEYS */;

--
-- Dumping data for table `<<prefix>>subadmin2`
--

/*!40000 ALTER TABLE `<<prefix>>subadmin2` DISABLE KEYS */;
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.08.0705','BO','BO.08','Provincia Chiquitos','Provincia Chiquitos',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.08.0712','BO','BO.08','Provincia Ángel Sandoval','Provincia Angel Sandoval',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.01.0103','BO','BO.01','Provincia Zudáñez','Provincia Zudanez',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.01.0106','BO','BO.01','Provincia Yamparáez','Provincia Yamparaez',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.03.0804','BO','BO.03','Provincia Yacuma','Provincia Yacuma',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.08.0702','BO','BO.08','Provincia Warnes','Provincia Warnes',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.08.0703','BO','BO.08','Provincia Velasco','Provincia Velasco',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.08.0708','BO','BO.08','Provincia Vallegrande','Provincia Vallegrande',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.03.0802','BO','BO.03','Provincia Vaca Diez','Provincia Vaca Diez',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.01.0104','BO','BO.01','Provincia Tomina','Provincia Tomina',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.07.0501','BO','BO.07','Provincia Tomás Frías','Provincia Tomas Frias',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.05.0411','BO','BO.05','Tomás Barrón','Tomas Barron',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.02.0311','BO','BO.02','Provincia Tapacarí','Provincia Tapacari',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.0211','BO','BO.04','Provincia Sud Yungas','Provincia Sud Yungas',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.07.0510','BO','BO.07','Sur Lípez','Sur Lipez',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.01.0109','BO','BO.01','Sur Cinti','Sur Cinti',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.07.0508','BO','BO.07','Sur Chichas','Sur Chichas',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.05.0410','BO','BO.05','Saucarí','Saucari',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.08.0706','BO','BO.08','Provincia Sara','Provincia Sara',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.08.3904660','BO','BO.08','Provincia Obispo Santistevan','Provincia Obispo Santistevan',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.05.0413','BO','BO.05','Provincia San Pedro de Totora','Provincia San Pedro de Totora',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.05.0404','BO','BO.05','Provincia Sajama','Provincia Sajama',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.07.0503','BO','BO.07','Provincia Cornelio Saavedra','Provincia Cornelio Saavedra',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.07.0502','BO','BO.07','Provincia Rafael Bustillo','Provincia Rafael Bustillo',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.02.0309','BO','BO.02','Provincia Quillacollo','Provincia Quillacollo',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.07.0512','BO','BO.07','Provincia Antonio Quijarro','Provincia Antonio Quijarro',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.02.0314','BO','BO.02','Provincia Punata','Provincia Punata',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.05.0406','BO','BO.05','Provincia Poopó','Provincia Poopo',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.05.0407','BO','BO.05','Provincia Pantaleón Dalence','Provincia Pantaleon Dalence',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.0203','BO','BO.04','Provincia Pacajes','Provincia Pacajes',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.01.0101','BO','BO.01','Provincia Oropeza','Provincia Oropeza',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.0202','BO','BO.04','Provincia Omasuyos','Provincia Omasuyos',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.09.0606','BO','BO.09','Provincia O’Connor','Provincia O\'Connor',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.08.0711','BO','BO.08','Provincia Ñuflo de Chávez','Provincia Nuflo de Chavez',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.0214','BO','BO.04','Provincia Nor Yungas','Provincia Nor Yungas',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.07.0509','BO','BO.07','Provincia Nor Lípez','Provincia Nor Lipez',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.01.0107','BO','BO.01','Provincia Nor Cinti','Provincia Nor Cinti',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.07.0506','BO','BO.07','Provincia Nor Chichas','Provincia Nor Chichas',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.06.0901','BO','BO.06','Provincia Nicolás Suárez','Provincia Nicolas Suarez',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.0201','BO','BO.04','Provincia Murillo','Provincia Murillo',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.0205','BO','BO.04','Provincia Muñecas','Provincia Munecas',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.03.0805','BO','BO.03','Provincia Moxos','Provincia Moxos',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.07.0515','BO','BO.07','Provincia Modesto Omiste','Provincia Modesto Omiste',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.02.0313','BO','BO.02','Provincia Mizque','Provincia Mizque',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.09.0605','BO','BO.09','Provincia Méndez','Provincia Mendez',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.03.0806','BO','BO.03','Provincia Marbán','Provincia Marban',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.06.0902','BO','BO.06','Provincia Manuripi','Provincia Manuripi',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.08.0713','BO','BO.08','Provincia Manuel María Caballero','Provincia Manuel Maria Caballero',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.0217','BO','BO.04','Provincia Manco Kapac','Provincia Manco Kapac',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.03.0807','BO','BO.03','Provincia Mamoré','Provincia Mamore',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.06.0903','BO','BO.06','Provincia Madre de Dios','Provincia Madre de Dios',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.01.0110','BO','BO.01','Provincia Luis Calvo','Provincia Luis Calvo',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.0212','BO','BO.04','Provincia Los Andes','Provincia Los Andes',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.0209','BO','BO.04','Provincia Loayza','Provincia Loayza',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.05.0405','BO','BO.05','Sud Carangas Province','Sud Carangas Province',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.07.3911502','BO','BO.07','José María Linares','Jose Maria Linares',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.0206','BO','BO.04','Provincia Larecaja','Provincia Larecaja',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.05.0408','BO','BO.05','Provincia Ladislao Cabrera','Provincia Ladislao Cabrera',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.0215','BO','BO.04','Provincia Abel Iturralde','Provincia Abel Iturralde',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.03.0808','BO','BO.03','Provincia Iténez','Provincia Itenez',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.0210','BO','BO.04','Provincia Inquisivi','Provincia Inquisivi',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.0208','BO','BO.04','Provincia Ingavi','Provincia Ingavi',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.08.0704','BO','BO.08','Provincia Ichilo','Provincia Ichilo',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.01.0105','BO','BO.01','Provincia Hernando Siles','Provincia Hernando Siles',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.0218','BO','BO.04','Provincia Gualberto Villarroel','Provincia Gualberto Villarroel',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.09.0603','BO','BO.09','Provincia Gran Chaco','Provincia Gran Chaco',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.02.0308','BO','BO.02','Provincia Germán Jordán','Provincia German Jordan',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.03.3915596','BO','BO.03','Provincia General José Ballivián','Provincia General Jose Ballivian',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.06.3915598','BO','BO.06','Federico Román','Federico Roman',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.07.3915603','BO','BO.07','Provincia General Bilbao','Provincia General Bilbao',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.0207','BO','BO.04','Franz Tomayo','Franz Tomayo',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.08.0709','BO','BO.08','Provincia Florida','Provincia Florida',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.02.0304','BO','BO.02','Provincia Esteban Arze','Provincia Esteban Arze',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.07.0514','BO','BO.07','Provincia Daniel Campos','Provincia Daniel Campos',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.08.0707','BO','BO.08','Provincia Cordillera','Provincia Cordillera',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.07.0504','BO','BO.07','Provincia Chayanta','Provincia Chayanta',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.07.0505','BO','BO.07','Provincia Charcas','Provincia Charcas',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.02.0310','BO','BO.02','Chapare','Chapare',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.09.0601','BO','BO.09','Cercado','Cercado',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.05.0401','BO','BO.05','Provincia Cercado','Provincia Cercado',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.02.0301','BO','BO.02','Provincia Cercado','Provincia Cercado',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.03.0801','BO','BO.03','Provincia Cercado','Provincia Cercado',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.02.0312','BO','BO.02','Provincia Carrasco','Provincia Carrasco',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.05.3922026','BO','BO.05','Provincia Carangas','Provincia Carangas',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.02.0307','BO','BO.02','Provincia Capinota','Provincia Capinota',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.02.0302','BO','BO.02','Provincia Campero','Provincia Campero',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.0204','BO','BO.04','Provincia Camacho','Provincia Camacho',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.01.0108','BO','BO.01','Provincia Belisario Boeto','Provincia Belisario Boeto',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.0216','BO','BO.04','Provincia Bautista Saavedra','Provincia Bautista Saavedra',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.01.0102','BO','BO.01','Provincia Azurduy','Provincia Azurduy',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.02.0303','BO','BO.02','Provincia Ayopaya','Provincia Ayopaya',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.09.0604','BO','BO.09','Provincia Avilés','Provincia Aviles',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.05.0402','BO','BO.05','Provincia Abaroa','Provincia Abaroa',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.05.3923586','BO','BO.05','Provincia Sabaya','Provincia Sabaya',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.02.0306','BO','BO.02','Provincia Arque','Provincia Arque',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.0213','BO','BO.04','Provincia Aroma','Provincia Aroma',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.09.0602','BO','BO.09','Provincia Arce','Provincia Arce',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.02.0305','BO','BO.02','Provincia Arani','Provincia Arani',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.08.0701','BO','BO.08','Provincia Andrés Ibáñez','Provincia Andres Ibanez',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.07.0507','BO','BO.07','Alonso de Ibáñez','Alonso de Ibanez',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.06.0904','BO','BO.06','Provincia Abuná','Provincia Abuna',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.02.7576102','BO','BO.02','Bolivar','Bolivar',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.02.8335405','BO','BO.02','Tiraque Province','Tiraque Province',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.05.10400355','BO','BO.05','Nor Carangas Province','Nor Carangas Province',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.05.10400859','BO','BO.05','Sebastian Pagador Province','Sebastian Pagador Province',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.11184247','BO','BO.04','Caranavi','Caranavi',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.04.11184248','BO','BO.04','José Manuel Pando','Jose Manuel Pando',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.05.11184249','BO','BO.05','Puerto de Mejillones','Puerto de Mejillones',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.05.11184250','BO','BO.05','Litoral de Atacama','Litoral de Atacama',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.07.11184251','BO','BO.07','Enrique Baldivieso','Enrique Baldivieso',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.08.11184252','BO','BO.08','German Busch','German Busch',1);
INSERT INTO `<<prefix>>subadmin2` (`code`, `country_code`, `subadmin1_code`, `name`, `asciiname`, `active`) VALUES ('BO.08.11184253','BO','BO.08','Guarayos','Guarayos',1);
/*!40000 ALTER TABLE `<<prefix>>subadmin2` ENABLE KEYS */;

--
-- Dumping data for table `<<prefix>>cities`
--

/*!40000 ALTER TABLE `<<prefix>>cities` DISABLE KEYS */;
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','San Matías','San Matias',-58.4,-16.3667,'P','PPL','BO.08','BO.08.0712',6352,'America/La_Paz',1,'2017-02-11 23:00:00','2017-02-11 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Roboré','Robore',-59.7614,-18.3347,'P','PPL','BO.08','BO.08.0705',9882,'America/La_Paz',1,'2017-02-05 23:00:00','2017-02-05 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Puerto Quijarro','Puerto Quijarro',-57.7667,-17.7833,'P','PPL','BO.08',NULL,10392,'America/La_Paz',1,'2012-01-17 23:00:00','2012-01-17 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Yacuiba','Yacuiba',-63.6775,-22.0164,'P','PPLA2','BO.09','BO.09.0603',82803,'America/La_Paz',1,'2014-11-29 23:00:00','2014-11-29 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Warnes','Warnes',-63.1678,-17.5163,'P','PPL','BO.08',NULL,22036,'America/La_Paz',1,'2015-06-11 23:00:00','2015-06-11 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Villazón','Villazon',-65.5942,-22.0866,'P','PPL','BO.07',NULL,30253,'America/La_Paz',1,'2019-03-31 23:00:00','2019-03-31 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Villa Yapacaní','Villa Yapacani',-63.8333,-17.4,'P','PPL','BO.08',NULL,18187,'America/La_Paz',1,'2012-02-01 23:00:00','2012-02-01 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Villamontes','Villamontes',-63.469,-21.2624,'P','PPL','BO.09',NULL,18761,'America/La_Paz',1,'2013-01-10 23:00:00','2013-01-10 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Vallegrande','Vallegrande',-64.1061,-18.4892,'P','PPL','BO.08',NULL,8422,'America/La_Paz',1,'2013-01-10 23:00:00','2013-01-10 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Uyuni','Uyuni',-66.825,-20.4597,'P','PPL','BO.07',NULL,10293,'America/La_Paz',1,'2013-10-26 23:00:00','2013-10-26 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Tupiza','Tupiza',-65.7188,-21.4435,'P','PPL','BO.07',NULL,22233,'America/La_Paz',1,'2013-01-10 23:00:00','2013-01-10 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Trinidad','Trinidad',-64.9,-14.8333,'P','PPLA','BO.03',NULL,84259,'America/La_Paz',1,'2014-06-01 23:00:00','2014-06-01 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Tiquipaya','Tiquipaya',-66.2158,-17.338,'P','PPL','BO.02',NULL,53904,'America/La_Paz',1,'2017-12-13 23:00:00','2017-12-13 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Tarija','Tarija',-64.7296,-21.5355,'P','PPLA','BO.09',NULL,159269,'America/La_Paz',1,'2010-01-28 23:00:00','2010-01-28 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Tarata','Tarata',-66.0213,-17.609,'P','PPL','BO.02',NULL,8043,'America/La_Paz',1,'2013-05-07 23:00:00','2013-05-07 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Sucre','Sucre',-65.2627,-19.0333,'P','PPLC','BO.01',NULL,224838,'America/La_Paz',1,'2019-09-04 23:00:00','2019-09-04 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Santiago del Torno','Santiago del Torno',-63.3812,-17.9867,'P','PPL','BO.08',NULL,15543,'America/La_Paz',1,'2013-05-07 23:00:00','2013-05-07 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Santa Rosa del Sara','Santa Rosa del Sara',-63.5951,-17.1092,'P','PPL','BO.08',NULL,5251,'America/La_Paz',1,'2013-05-07 23:00:00','2013-05-07 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Santa Cruz de la Sierra','Santa Cruz de la Sierra',-63.1812,-17.7863,'P','PPLA','BO.08',NULL,1364389,'America/La_Paz',1,'2016-11-03 23:00:00','2016-11-03 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Santa Ana de Yacuma','Santa Ana de Yacuma',-65.4269,-13.7441,'P','PPL','BO.03',NULL,12783,'America/La_Paz',1,'2017-09-11 23:00:00','2017-09-11 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','San Pedro','San Pedro',-68.8506,-16.2372,'P','PPL','BO.04',NULL,5002,'America/La_Paz',1,'2011-12-05 23:00:00','2011-12-05 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','San Julian','San Julian',-62.8667,-17.7833,'P','PPL','BO.08',NULL,7706,'America/La_Paz',1,'2019-04-10 23:00:00','2019-04-10 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','San Ignacio de Velasco','San Ignacio de Velasco',-60.95,-16.3667,'P','PPL','BO.08',NULL,23569,'America/La_Paz',1,'2017-05-07 23:00:00','2017-05-07 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Sacaba','Sacaba',-66.0383,-17.398,'P','PPL','BO.02',NULL,107628,'America/La_Paz',1,'2017-12-05 23:00:00','2017-12-05 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Rurrenabaque','Rurrenabaque',-67.5278,-14.4412,'P','PPL','BO.03',NULL,11749,'America/La_Paz',1,'2008-03-21 23:00:00','2008-03-21 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Riberalta','Riberalta',-66.0631,-11.0065,'P','PPL','BO.03','BO.03.0802',74014,'America/La_Paz',1,'2016-12-20 23:00:00','2016-12-20 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Reyes','Reyes',-67.3362,-14.2952,'P','PPL','BO.03','BO.03.3915596',7376,'America/La_Paz',1,'2015-06-12 23:00:00','2015-06-12 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Quillacollo','Quillacollo',-66.2784,-17.3923,'P','PPL','BO.02',NULL,87309,'America/La_Paz',1,'2017-09-11 23:00:00','2017-09-11 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Punata','Punata',-65.8347,-17.5423,'P','PPL','BO.02',NULL,15194,'America/La_Paz',1,'2013-05-07 23:00:00','2013-05-07 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Potosí','Potosi',-65.7531,-19.5836,'P','PPLA','BO.07',NULL,141251,'America/La_Paz',1,'2017-02-11 23:00:00','2017-02-11 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Portachuelo','Portachuelo',-63.3928,-17.3517,'P','PPL','BO.08',NULL,11485,'America/La_Paz',1,'2013-05-07 23:00:00','2013-05-07 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Patacamaya','Patacamaya',-67.9217,-17.2358,'P','PPL','BO.04',NULL,12260,'America/La_Paz',1,'2013-05-07 23:00:00','2013-05-07 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Pailón','Pailon',-62.75,-17.65,'P','PPL','BO.08',NULL,9304,'America/La_Paz',1,'2012-01-17 23:00:00','2012-01-17 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Oruro','Oruro',-67.15,-17.9833,'P','PPLA','BO.05',NULL,208684,'America/La_Paz',1,'2012-01-17 23:00:00','2012-01-17 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Montero','Montero',-63.2505,-17.3387,'P','PPL','BO.08',NULL,88616,'America/La_Paz',1,'2013-05-07 23:00:00','2013-05-07 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Monteagudo','Monteagudo',-63.9546,-19.7999,'P','PPL','BO.01',NULL,8289,'America/La_Paz',1,'2013-01-10 23:00:00','2013-01-10 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Mizque','Mizque',-65.3402,-17.941,'P','PPL','BO.02',NULL,30481,'America/La_Paz',1,'2009-10-15 23:00:00','2009-10-15 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Mineros','Mineros',-63.231,-17.1188,'P','PPL','BO.08',NULL,14385,'America/La_Paz',1,'2018-12-04 23:00:00','2018-12-04 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Llallagua','Llallagua',-66.5839,-18.4243,'P','PPL','BO.07',NULL,28069,'America/La_Paz',1,'2013-01-10 23:00:00','2013-01-10 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','La Paz','La Paz',-68.15,-16.5,'P','PPLG','BO.04',NULL,812799,'America/La_Paz',1,'2019-09-04 23:00:00','2019-09-04 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','La Bélgica','La Belgica',-63.2167,-17.55,'P','PPL','BO.08',NULL,5501,'America/La_Paz',1,'2012-01-18 23:00:00','2012-01-18 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Huanuni','Huanuni',-66.8358,-18.289,'P','PPL','BO.05',NULL,15492,'America/La_Paz',1,'2019-03-31 23:00:00','2019-03-31 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Guayaramerín','Guayaramerin',-65.3581,-10.8258,'P','PPL','BO.03','BO.03.0802',36008,'America/La_Paz',1,'2017-10-01 23:00:00','2017-10-01 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Cotoca','Cotoca',-63.05,-17.8167,'P','PPL','BO.08',NULL,18347,'America/La_Paz',1,'2019-02-20 23:00:00','2019-02-20 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Concepción','Concepcion',-60.9,-16.4333,'P','PPL','BO.08',NULL,6900,'America/La_Paz',1,'2019-04-10 23:00:00','2019-04-10 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Colchani','Colchani',-66.9333,-20.3,'P','PPL','BO.07',NULL,11988,'America/La_Paz',1,'2012-01-18 23:00:00','2012-01-18 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Cochabamba','Cochabamba',-66.1568,-17.3895,'P','PPLA','BO.02',NULL,900414,'America/La_Paz',1,'2012-01-18 23:00:00','2012-01-18 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Cobija','Cobija',-68.7692,-11.0267,'P','PPLA','BO.06',NULL,26585,'America/La_Paz',1,'2010-08-20 23:00:00','2010-08-20 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Cliza','Cliza',-65.9325,-17.5878,'P','PPL','BO.02',NULL,8654,'America/La_Paz',1,'2013-05-07 23:00:00','2013-05-07 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Chimoré','Chimore',-65.1533,-16.9942,'P','PPL','BO.02',NULL,5147,'America/La_Paz',1,'2016-10-01 23:00:00','2016-10-01 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Challapata','Challapata',-66.7705,-18.9021,'P','PPL','BO.05',NULL,8016,'America/La_Paz',1,'2013-01-10 23:00:00','2013-01-10 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Capinota','Capinota',-66.2608,-17.7111,'P','PPL','BO.02',NULL,5157,'America/La_Paz',1,'2013-05-07 23:00:00','2013-05-07 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Camiri','Camiri',-63.5183,-20.0385,'P','PPL','BO.08',NULL,27961,'America/La_Paz',1,'2013-01-10 23:00:00','2013-01-10 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Bermejo','Bermejo',-64.3372,-22.7321,'P','PPL','BO.09',NULL,35411,'America/La_Paz',1,'2017-12-13 23:00:00','2017-12-13 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Ascensión','Ascension',-63.0833,-15.7,'P','PPL','BO.08',NULL,14429,'America/La_Paz',1,'2012-01-18 23:00:00','2012-01-18 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Aiquile','Aiquile',-65.1807,-18.2041,'P','PPL','BO.02',NULL,8224,'America/La_Paz',1,'2009-10-15 23:00:00','2009-10-15 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Achacachi','Achacachi',-68.6833,-16.05,'P','PPL','BO.04',NULL,8447,'America/La_Paz',1,'2012-01-18 23:00:00','2012-01-18 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','Ascención de Guarayos','Ascencion de Guarayos',-63.1885,-15.893,'P','PPLL','BO.08',NULL,18816,'America/La_Paz',1,'2017-12-12 23:00:00','2017-12-12 23:00:00');
INSERT INTO `<<prefix>>cities` (`country_code`, `name`, `asciiname`, `longitude`, `latitude`, `feature_class`, `feature_code`, `subadmin1_code`, `subadmin2_code`, `population`, `time_zone`, `active`, `created_at`, `updated_at`) VALUES ('BO','San Borja','San Borja',-66.7495,-14.8519,'P','PPL','BO.03',NULL,24610,'America/La_Paz',1,'2020-01-23 23:00:00','2020-01-23 23:00:00');
/*!40000 ALTER TABLE `<<prefix>>cities` ENABLE KEYS */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed
